### ISSUE TITLE
Class definition practices 

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#128]
@ileppe 
Below are few issues I've noticed, maybe we can add these into developer documentation: 
If there is a convention to suggest documentation instead of opening an issue, please let me know :)

**i) Do not leave white space in Format names like in the Flip Angle it should be Flip angle**

You can define their units between parentheses, its ok

Bad Example:
Prot = struct('MT',struct('Format',{{‘Flip Angle''TR (s)''Offset (Hz)'}},...

Good Example:
Prot = struct('MT',struct('Format',{{‘FlipAngle''TR (s)''Offset (Hz)'}},...

**ii) Make sure that Format fields are always cell**

Bad example:
Prot  = struct('MET2data',struct('Format',{'EchoTime (ms)'})) % In this case EchoTime is a 1XN char

Good example:
Prot  = struct('MET2data',struct('Format’,{{'EchoTime (ms)’}})) % In this case EchoTime is a 1X1 cell.

**iii) Please make sure that Model.MRIinputs names are the same with Demo file names.**

Bad example:

NoiseLevel.MRIinputs: Data4D NoiseMask
File names: 4DData.nii.gz NoiseMask.nii.gz

In this case auto batch generation won’t face a run-time error but will generate an incomplete script.

Good example:

NoiseLevel.MRIinputs: Data4D NoiseMask
File names: Data4D.nii.gz NoiseMask.nii.gz

**Comment by tanguyduval** [comment]
Ideally, all these issues should make Travis crash and report a clear error :). Edit batch_example_test if needed! Currently the errors reported are often obscure, I didn't take a look at that..

**Comment by agahkarakuzu** [comment]
I think the way functions built around them prevents runtime errors, making Travis remain agnostic. Evidently, operations carried on. Yet, when it comes to building something systematic on top of them, like the bash_example generator, such tiny issues become annoying runtime errors. 

To trouble free Travis reports! :)

**Comment by agahkarakuzu** [comment]
qMT_SIRFSE MRIinputs:

- MTData
- R1Map 
- Mask

qMT_SIRFSE Demo folders: 

Mask.nii.gz
MTData.nii.gz 

**Fit still works without R1Map. Should we remove R1Map from MRInputs list?**

**Comment by mathieuboudreau** [comment]
@agahkarakuzu the original qMT_SIRFSE paper ("Quantitative Magnetization Transfer Imaging in Human
Brain at 3 T via Selective Inversion Recovery", Dortch et al. 2011) mentions no additional qMRI maps are required (B0, B1, or R1/T1), so it would make sense to remove R1Map from the MRInputs list.

What's the mismatch for MTSAT? Is Mask not in the MRIinputs list? Is this related to issue number #86 ?

**Comment by agahkarakuzu** [comment]
For MTSAT, yes this is the same issue :) We can remove in hackathon now.

**Comment by mathieuboudreau** [comment]
I don't think we should remove the Mask from the MRIinputs, but rather apply the mask within the method! I can do that during the hackathon.
