### ISSUE TITLE
B1 map filtering post-processing feature

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#135]
Just putting this here as a note to myself to add this feature in the future.

A lot of groups filter/smooth B1 maps because they're expected to be slowly varying in nature. I think it would be a good feature to have for qMRLab along with some options for the filtering. I have one implemented in Matlab in a private repo which I've used before, so I'll add it to a B1 map superclass so that all B1 maps in the future can share it. I also have AFI and Bloch-Siegert B1 mapping code that I could add as Models at the same time.

**Comment by ileppe** [comment]
@mathieuboudreau As we discussed, I am going to look into different smoothing options for the B1maps, as well as the different acquisition methods:
- AFI
- Bloch-Siegert
- tfl_b1map (product from Siemens)

@agahkarakuzu I will start from #290
I'm open to any input, thanks!

**Comment by mathieuboudreau** [comment]
Great, thanks! Something that I had in mind, when I first was pondering about this, is that maybe smoothing/filtering could be created in its own class, that B1 maps (and any other model that we might want to filter) would inherit. That way, if new filters are added, or old ones are changed, they will all be applied.

Looking forward to this - let me know if I can help / pick up some weight as well!

**Comment by ileppe** [comment]
Yes! This is what I had in mind as well, I was thinking something in `src/Common/`, much like `FitData.m`? Although it's not really a class...

**Comment by mathieuboudreau** [comment]
The thing with a class, is that you could then write in the GUI: If (class) has (filter method), add these (buttons), or something like that. Something like what we do with AbstractClass – B1 filtering could also be an abstract class (i.e. you can create an instance of that class), but just a collection of methods (i.e. functions) that are collectively added if another class inherits it.

src/Common/ would be a good spot to add this!

**Comment by ileppe** [comment]
If I understand correctly, something like: `classdef b1_dam < AbstractModel & Filter` i.e. this particular model inherits from 2 classes, and `Filter` is another abstract class with different methods for filtering?

**Comment by mathieuboudreau** [comment]
Yup, that's what I had in mind. But I didn't look into further, and it was just a suggestion. Feel free to write it in whatever way you think it will work best!

**Comment by mathieuboudreau** [comment]
The other thing we could do, is make it a non-abstract class, just a class (i.e. method), which you could load any images, and filter them, save them as output, which you would then go to the qMR method and load that filtered image (whatever it may be). I think both might work, and this might be easier to do in the GUI, so up to you!

**Comment by ileppe** [comment]
Do you mean load it up like any other model?

**Comment by mathieuboudreau** [comment]
(@ileppe and I continued our discussion to clarify a few planning details on a phone call, to avoid spamming you all too much today.)

**Comment by ileppe** [comment]
I'll also be adding an optional mask, it's better to exclude the background when smoothing.

**Comment by mathieuboudreau** [comment]
Sounds good – the challenge with masked smoothing will be how to handle the edges. I think there are a lot of suggestions out there on how to do that (e.g. interpolating outside the edges first), but I havent done anything like that.

**Comment by ileppe** [comment]
Ok, a case of "damned if you do, damned if you don't" I'll look into it! I've also seen just setting spurious b1 values (e.g. <0.5) to the nominal value (i.e. 1) before smoothing...

**Comment by mathieuboudreau** [comment]
Yup haha! If you do that before smoothing, maybe you could report a map of which voxels were "spurius" and replaced (sort of like what we do with residual maps in other models)?

**Comment by mathieuboudreau** [comment]
Great – thanks Toby! I used to do something similar using N3's spline smoothing feature in MINC. I feel like a combination of both might be better (e.g. do a polynomial fit to get an estimate outside the mask or at spurious values, and then do gaussian/median filtering with those in place to avoid edge effects), but my gut feelings have not always been right before haha.

**Comment by ileppe** [comment]
I've been using this implementation of spline smoothing, http://www.biomecardio.com/matlab/smoothn_doc.html and have been quite happy. I was going to implement a couple of flavors and let the user choose (maybe always using spline/polynomials for edges?):
- gaussian
- median
- spline
- ...

**Comment by agahkarakuzu** [comment]
Closed #317.

**Comment by em-blue** [comment]
> @mathieuboudreau As we discussed, I am going to look into different smoothing options for the B1maps, as well as the different acquisition methods:
> 
> * AFI
> * Bloch-Siegert
> * tfl_b1map (product from Siemens)
> 
> @agahkarakuzu I will start from #290
> I'm open to any input, thanks!

Hi @mathieuboudreau - I'm looking for construct B1 maps via the Bloch-Siegert method, is qMRLab working on this / is this something I should contribute?

**Comment by agahkarakuzu** [comment]
@em-blue you are more than welcome to contribute, that would be a nice addition!

I am not sure if @mathieuboudreau have  started implementing it, which is definitely not an obstacle to coordinate.

**Comment by mathieuboudreau** [comment]
Hi @em-blue !

Yes, this would be a great contribution!

As I mentioned in our DMs, I released the code for my B1 mapping paper recently, and the Bloch Siegert function is here: https://github.com/mathieuboudreau/B1Paper_Analysis/blob/master/src/b1/fitDataBSB1.m
* It'll need some refactoring, and probably some explanations/thinking about what some of the code does. My apologies for having "magic numbers" in there, most of them are are constants that I remember why they are there (e.g. 4096 was because of the datatype of the phase data I used being signed and having a range of +- 4096 to represent the phase angle).

The biggest hurdle I've always seen for this being a qMRLab module is that the `AmpInt` and `Kbs` parameters need to be known ahead of time, or calculated from the RF pulse curve. I've dug in a bit deeper in my old hard drives to look for some of the code I used to generate the RF pulse curves into a *.pta format for Siemens and also calculate the AmpInt and Kbs values from those *.pta files. I just found them, and uploaded them on GitHub: https://github.com/mathieuboudreau/bloch-sieg-pulse-tools. 
* Again, these are not as well commented as I would like since they're from my early coding/PhD days, but at least they're here now!

I've also taken the liberty of extracting the relevant section of my PhD thesis where I discuss Bloch-Siegert mapping, which is available here: https://drive.google.com/file/d/17PKUa9eag66USoDjCn2aKDsni971zdcl/view?usp=sharing
* My entire thesis should also be available for free on the McGill website here: https://escholarship.mcgill.ca/concern/theses/73666714q?locale=en

Hope some of this info helps!

**Comment by mathieuboudreau** [comment]
Hi @em-blue,

I uploaded one of my Bloch-Siegert datasets on OSF: https://osf.io/c9mqj/.

We should maybe open up a new issue for this, since this one is closed and unrelated to Bloch-Siegert now. Let us know if you have any questions or want to discuss more.
