### ISSUE TITLE
Singleton Dimensions 

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#163]
I run into this problem with inversion_recovery, might be present in other models as well. Number of volumetric elements (nV) is calculated from data size as follows:

`[x,y,z,nT] = size(qData); 
nV = x*y*z; `

Sample IR data dimension is 128X128X1X9. Code fails to proceed if data is given w/o singleton  element (e.g. 128X128X9 ) due to dimension mismatch as one would expect. 

If we lay down presence of singleton dimension as a condition (do we?), we should better document it. We should re-check & make sure that we use a standard approach for dimensionality control and vectorization of the data.

**Comment by mathieuboudreau** [comment]
Urgh, the missing singleton dimension for single-slice and how it is handled was the source of a lot of frustration for me in my early PhD days, I encountered it in a lot of different software (e.g. MINC tools, NIAK).

I think we should either 1) Verify and handle this when the data is first loaded (i.e. if the singleton dimension is missing, add it here), or 2) Handle it at locations are you have shown above (if the size of qData only has 3 dimensions, calculate nV one way, if it has 4, calculate it another way).

I think the first option might be cleaner and easier to debug in the long haul.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau thank you for the update, I will look into this deeper and create a systematic solution to that. 

There is another thing that attracted my attention with ivnersion_recovery. Does Barral's IR fitting method use fitting options (st,lb,ub,fx)? If I remember correctly, it uses a grid search based NLLS which does not employ Matlab's fitting routines. I guess those (st,lb,ub,fx) assignments are just verbosity?

**Comment by mathieuboudreau** [comment]
Hmm, not sure, it's been a while since I've looked under the hood of Barral's code. 

Maybe @ileppe would know more about that?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau @ileppe I just made a coarse check by commenting them out and fitting has been completed without any errors. I guess we should also check the consistency of class defs with methods and get rid of unnecessary attributes.

**Comment by ileppe** [comment]
I don't think the (st,lb,ub,fx) are used in the fitting, but they can be controlled for the simulation functionality. Re: data dimensions: I've begun handling this type of thing in my 'error-catch' branch, see #156. The idea being that before `FitData` is run, a generic error checker would pick up these discrepancies and in this case correct the data (if that's what we decide)

**Comment by ileppe** [comment]
@agahkarakuzu Can you please send me data that is causing this issue?

**Comment by agahkarakuzu** [comment]
Resolved. Merged. #169
