### ISSUE TITLE
Crossover between qMRLab and QUIT?

### ISSUE THREAD

**Issue by spinicist** [qMRLab/qMRLab#165]
Hi,

Excuse the self-advertising, but several years ago I started a C++ library with similar goals as qMRLab, which is available [here](https://github.com/spinicist/QUIT). It does not include as many methods as qMRLab, mainly because I'm the only person who works on it so it only gets methods that I need to process. I've almost finished a large set of improvements (available in the Modules branch), so I'm hoping to release version 2.0 in the near future. I took a fairly similar approach to qMRLab in trying to define a general "Model" or "Algorithm" setup that can be re-used fairly easily.

I think it's great that qMRLab has been set up and there is so much interest in it. I wish it had been around 6 years ago when I first started. I don't want to get into a language war - there are advantages and disadvantages to every language. I'm putting this up here so:

1. If anyone wants a command-line version of a qMRI method, there's a possibility it's available in QUIT. If I have time, I like adding methods to it, but I mostly don't have time.
2. If anyone knows or fancies learning C++ and helping out, I'd be glad of it

Hopefully I'll catch some or all of you at ISMRM,
Toby

**Comment by agahkarakuzu** [comment]
Hi Tobias, 

Thank you for sharing your kind remarks with us. It is intriguing to see the kindship of two independent object oriented approaches that have been embarked on for qMR processing, despite the differences regarding the selection of development environments. It somewhat reinforces the promise of such attempts in standardizing qMR routines, being indicative of a sober framework :) 

Keeping the ultimate aim of providing people with a community driven, user friendly and a reproducible qMR platform as the common ground for discussion; enabling cross-language accessibility would surely be a big plus. There is no doubt that such crossover would come with its own set of technical challanges, especially in terms of generation of almost identical outputs in different platforms. 

Although we dont have plans to implement methods in platforms other than Octave/Matlab in foreseeable future, I would love to discuss more about reconciler strategies to make the most useful out of overlapping portion of our efforts by taking reproducibility into account. 

These are mostly my personal remarks. I am open to discuss more. Maybe we can set a meeting time/place at ISMRM? It would make it easier for us all and ensures that we won't miss out on the opportunity to share more insights with each other. 
 
Thank you once again,
Agah

**Comment by mathieuboudreau** [comment]
@spinicist I starred your repo a long time ago, but forgot about it! Thanks for bringing this up here again!

qMRLab is the brainchild of Nikola Stikov and Julien Cohen-Adad at the Neuropoly in Montreal. They are very open to collaborations, and I'm sure learning more about each other's code can only help improve our own, and the qMRI field as a whole!

We sometimes do mini-hackathons to do coordinated pushes on qMRLab - it could be a good idea in the future to do one to explore yours, and vice versa. Just a thought!

Best,

Mathieu

**Comment by jcohenadad** [comment]
Hi Tobias,

thank you for bringing this to our attention and sorry for the oversight. What i see though is that qMRLab and QUIT are not completely overlapping, in the sense that one of qMRLab's mission is to enable people to simulate data from models and play around with fitting equations using a GUI (that's the idea of the "Lab" in qMRLab). I agree C++ is the way to go for speed, and that's currently one of that major limitation of qMRLab. 

p.s. the link from QUIT does not appear in your first post so i'm adding it here: https://github.com/spinicist/QUIT

**Comment by spinicist** [comment]
Thanks all!

@jcohenadad Thanks for pointing out the broken link, I need to practice my Markdown.

I think the distinction you draw is exactly the one I would make. It is possible to simulate data in QUIT using the `qisignal` program - this is how I wrote my tests (simulate data, add noise, check you get reasonable parameter estimates back). However, this is not the focus of QUIT and I will never add a UI like the one qMRLab has (C++ GUIs are a nightmare in my opinion). 

My original focus with QUIT was having a high-speed set of programs for mcDESPOT processing, which is notoriously slow. Since then I've expanded it every time our site acquires a new type of data that we don't have processing for, which is exactly my rough plan for the future.

@agahkarakuzu Personally, I think the differences between Matlab and C++ are too big to do much direct cross-over. I know you could use MEX to write high-performance C/C++ code that qMRLab would then call, but I think that defeats the main point of qMRLab which is as an educational tool (people who only know Matlab wouldn't be able to follow the code). I think the most sensible route is simply for me (and others if they want to join in) to use qMRLab as a reference if they ever want to implement a command-line version of a particular technique.

@mathieuboudreau Yes, if I can I will get involved with your next hack-a-thon. Would be good to learn more about the qMRLab internals.
