### ISSUE TITLE
New model registration form

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#167]
Hey @agahkarakuzu,

Nice work on the new wiki section!  https://github.com/neuropoly/qMRLab/wiki/Guideline%3A-Adding-a-new-Model

One question: where/to whom should the dev making a new model submit the registration form?

Cheers,

Mathieu

**Comment by agahkarakuzu** [comment]
@mathieuboudreau thank you! This is one of the issues that I'd like to bring to the table on our next meeting. Same question goes for sharing sample data, we need a communication line to address such needs. Do you have any suggestions for that? 

What do you think about the current version of the registration form? 

As for wiki page, I reformed many things. Please let me know if there is anything you did not like or requires major improvement.

**Comment by mathieuboudreau** [comment]
One additional thing to note, regarding importing other methods as modules; it may not be sufficient to only provide the name of the source. Most open-source licenses require that the license file for their package be included in the repo if we use it. We should indicate this somewhere in the registration. form you made.

e.g. Our [MIT license](https://github.com/neuropoly/qMRLab/blob/master/LICENSE)

**Comment by mathieuboudreau** [comment]
@agahkarakuzu Ok will do! My defence is on Thursday, so I will take a closer look sometime shortly after that.

Cheers,

Mathieu

**Comment by agahkarakuzu** [comment]
Alright! Best of luck for your defense Dr. Boudreau :)

**Comment by agahkarakuzu** [comment]
This practice was not adapted. Please visit [wiki page](https://github.com/qMRLab/qMRLab/wiki/Guideline:-Adding-a-new-Model) for documentation regarding adding a new model.
