### ISSUE TITLE
Non-isotropic images should be scaled on the viewer

### ISSUE THREAD

**Issue by jcohenadad** [qMRLab/qMRLab#197]
State of qMRLab: 1de32d47b5457431f47a1ea92618774887d429c0

Current view:
<img width="1232" alt="current" src="https://user-images.githubusercontent.com/2482071/38540279-6e7c4212-3cd6-11e8-974a-6e5a9f3b17ec.png">

Should look like this:
<img width="1232" alt="stretch" src="https://user-images.githubusercontent.com/2482071/38540289-74c14eba-3cd6-11e8-8acb-f9687a24e954.png">

Proposed fix: use voxel dimension to stretch image on the 2D viewer appropriately.

**Comment by tanguyduval** [comment]
solved with the new viewer
