### ISSUE TITLE
Add synthetic phantom in example dataset

### ISSUE THREAD

**Issue by tanguyduval** [qMRLab/qMRLab#21]
- example: different agar concentration scanned on siemens

**Comment by mathieuboudreau** [comment]
Are the lineshapes required for phantoms currently already included in qMTLab (e.g. Lorentzian or Gaussian)? The superlorentzian lineshape is only valid for human tissues.

**Comment by jfcabana** [comment]
Yes they are. qMTLab includes Superlorentzian, Lorentzian and Gaussian lineshapes. If any other lineshapes could be useful, it should be quite easy to integrate them also.

**Comment by tanguyduval** [comment]
Thanks for this feedback! What is the lineshape that I should use in phantoms? Do you have a ref??

**Comment by mathieuboudreau** [comment]
In John Sled's 2001 paper title "Quantitative Imaging of Magnetization Transfer Exchange
and Relaxation Properties In Vivo Using MRI", he states that agar phantoms have Gaussian lineshapes. 

See the paragraph from this paper shown in this snapshot:

![sled2001](https://cloud.githubusercontent.com/assets/1421029/22634827/7ee07b3e-ec08-11e6-9d4b-e7dcee6e0269.png)
