### ISSUE TITLE
Results of comparing fitted VFA T1 map: qMRLab vs QUIT

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#221]
I took the time to compile and install @spinicist's [QUIT](https://github.com/spinicist/QUIT) software on my laptop, and was curious to compare fitting our VFA/DESPOT1 data that's on OSF using both our softwares.

One issue I hit upon was that there was a dimension mismatch in the headers of the single slice images (B1map and Mask) and the 3D volume that had a slice extracted (VFAdata). See my issue here: https://github.com/spinicist/QUIT/issues/11

However, thanks to @spinicist, I was able to change the header and got it working!

Here's the % difference of the T1 maps fitting using qMRLab and QUIT:

![comparison](https://user-images.githubusercontent.com/1421029/40378206-6f557fa6-5dcd-11e8-884b-ec925ab5bc3e.png)

Even though this is a very simple technique (VFA/DESPOT1) and case (2 flip angle), I was very happy to see that the difference between the T1 maps fitting using qMRLab (MATLAB) and QUIT (C++) was essentially close to numerical precision.

One large difference between the two though was the processing time. qMRLab fitted the data in about a minute, whereas QUIT fit the data almost instantly.

@agahkarakuzu since you are playing around with compiling MATLAB/Models, I'd recommend you do so with the VFA model and see what kind of speed improvement we can get. I suspect there's other places in the code we can optimise, but this should be a great benchmark case for you.

Another thing I think would be great to do would be including such a comparison  (qMRLab vs QUIT) in our TRAVIS CI tests using models we both share. However, it takes quite some time to compile QUIT, thus I don't think we have time within the time limit to install both Octave and compile the most recent version of QUIT – we may just need to occasionally compile it ourselves at a given version and install that compiled file in the TRAVIS virtual environment, which would be much quicker.

**Comment by tanguyduval** [comment]
Cool comparison, nice ;)
We need to optimize models indeed: Use the profiler and the compiler... Also defining variables type and size also helps (in my experience, if the fitting is much faster the second time you run it.. That mean you can optimize it!)

**Comment by spinicist** [comment]
Did the minute for qMRLab include the Matlab startup time? That's the bit that always depresses me the most when using Matlab 😉

**Comment by mathieuboudreau** [comment]
@spinicist  haha nope unfortunately – that's a minute already after Matlab and qMRLab GUI's are opened.

One time sink I think it taking up likely more than half that time though is that the GUI is updated every voxel to let the user know they've been fitted. Thousands and thousands of times. So removing that should substantially speed it up by itself.

**Comment by spinicist** [comment]
Yes, definitely! Minimising GUI updates is essential.
