### ISSUE TITLE
Quantitative Susceptibility Mapping (QSM) model

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#225]
**branch**: [qsm](https://github.com/neuropoly/qMRLab/tree/qsm)
**demo data\***: [OSF – qsm.zip](https://osf.io/rn572/)
**processing scripts\***: [qMRLab/src/Models_Functions/QSM/ – 5b6525a  – qsm branch](https://github.com/neuropoly/qMRLab/tree/5b6525aeb678bdeb0b70d1eaac8c9c2c7e9e0708/src/Models_Functions/QSM)
*Generously provided by [Dr. Berkin Bilgic](https://martinos.org/~berkin/index.html)
**publication**: [Bilgic, B. , Fan, A. P., Polimeni, J. R., Cauley, S. F., Bianciardi, M. , Adalsteinsson, E. , Wald, L. L. and Setsompop, K. (2014), Fast quantitative susceptibility mapping with L1‐regularization and automatic parameter selection. Magn. Reson. Med., 72: 1444-1459. doi:10.1002/mrm.25029](https://onlinelibrary.wiley.com/doi/abs/10.1002/mrm.25029)

Observations after running both processing scripts:

* Both processing scripts took ~2 hours to process (each) on my 3.1 GHz, dual-core, 16GB, MacBook Pro.
* Both processing scripts took an enormous amount of hard drive memory (close to 20 gb)
   * Lots of undeleted 3D complex arrays contributed to this, I think variable cleanup during the script is warranted.
* Both processing scripts share an large amount of codes
   * Converting the duplicates and the differences into functions should simplify how we want to design the model.

To do:
- [ ] Include a brain mask tool/function
   * Berkin used FSL's BET, and only provided the brain masks themselves
   * Integrate BET? Other available brain mask generator for Matlab? Deep learning brain masking tools that are out there?
- [x] Group together all hard-coded values (e.g. field strength, TE, resolution, algorithm params, etc.) together at the beginning of the scripts – these will be option parameters in the model.
- [x] Go through scripts and find last time each variable are needed, and if they should be saved as fitted outputs or deleted to free up space.
- [x] Convert all duplicate sections of scripts into functions.
   * Writing specific tests for each of these would be beneficial, if possible.
- [x] Convert differences of scripts (specific algorithms) into functions.
   * Writing specific tests for each of these would be beneficial, if possible.
- [x] Create empty template QSM model.
   * In the UnderDevelopment folder, to avoid TRAVIS tests.
- [x] Complete model

**other resources**:
* https://github.com/mathieuboudreau/qsm-tools

**Comment by agahkarakuzu** [comment]
Thank you @mathieuboudreau fascinating divide and conquer list! :) 💯 

> Include a brain mask tool/function

I'd suggest, again, including this to a workflow, keep that workflow, but not integrate tools in qMRLab. I will come up with an example next week hopefully. Both in Python and Matab/Octave.

> Deep learning brain masking tools that are out there?

I am following [Robert Brown's repo](https://github.com/robb-brown?tab=repositories) for this one, hopefully in few months he said in our last OSB chat.

> Both processing scripts took ~2 hours to process (each) on my 3.1 GHz, dual-core, 16GB, MacBook Pro.

First of all, you have a cool MacBook Pro 😮
 

Another advantage of workflows. If script allows in anyways,  workflow execution engine will understand and split it into multiple threads. (This is a bit advanced used case, because in general parallelization is done per subject, but possible). 

Now that we can run qMRLab on HPC (well, mt_sat only for now :) ), workflow managers will tap into lots of CPUs to go faster. But w/o them, it will be always running on a single core.

Another remark on overhead: I still believe that multiple function calls and attribute assignments per voxel are increasing the order of growth. This is something to test, I may be wrong.

**Comment by mathieuboudreau** [comment]
--Quick update--

Steps 2-6 are done, the scripts have been refactored out into functions, I made an improvement in the memory management of the algorithm (uses a max of 5-7 gigs of space instead of the old 20-30 gigs), and all customisable parameters have been grouped together at the beginning of the scripts.

See: https://github.com/neuropoly/qMRLab/tree/QSM/src/Models_Functions/QSM

Note that the scripts on this version still replicate the results of the original scripts.

Overall, I think it's much more clear how the algorithm works reading the scripts now than before, and I think the next step is actually creating the qMRLab model for it. @agahkarakuzu I can keep working on this when I have some extra time, or @agahkarakuzu if you want to take the lead again you're welcome to do so.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau Thank you so much for the intense effort, fascinating memory allocation improvement! I will start creating the model.

**Comment by mathieuboudreau** [comment]
Ok great @agahkarakuzu ! I'll share some potential design insights I might have with you when I see you next week, as there are a few different ways some options can be tackled (the padding he adds to the images in particular might be an issue in some more of the more advanced use-cases)

**Comment by mathieuboudreau** [comment]
Also, for now I think we should omit adding the brain mask tool, and it can be added later on if wanted.

**Comment by mathieuboudreau** [comment]
Rough QSM options pannel mockup that Agah and I brainstormed:

![qsm_mockup](https://user-images.githubusercontent.com/1421029/43848932-1642ffd4-9b02-11e8-8ceb-a4125f276326.png)

**Comment by mathieuboudreau** [comment]
A few other things to do:

* Refactor out the Chi-L2 calculation outside of the L2 optimization function (once we have L2 either through optimization or user input, Chi-L2 should be available to calculate).

* Add flag variable in scripts to decide on `once` or `iterative` background removal.

**Comment by mathieuboudreau** [comment]
More notes:

* Unlike other models, the mask needs to be a required input.

* for simplicity in implementation, let's require that the wrapped phase is an input (instead of supporting users who may of unwrapped their phase using a different external tool beforehand)

**Comment by agahkarakuzu** [comment]
@mathieuboudreau thank you for writing them down!

**Comment by agahkarakuzu** [comment]
@mathieuboudreau we've received an answer from Berkin, detailing it here:.

> Regarding naming

Berkin is not 100% sure about how to name. He noted that in the paper below it was called TVSB

https://onlinelibrary.wiley.com/doi/pdf/10.1002/mrm.25358

Maybe we can call it SB-QSM (Split Bregman - QSM), he added. 

>  Berkin said the refactored code looks great.  He also touched on regularization parameter estimation, that we already discussed: 

Users can be allowed to enter these parameters manually to skip these time consuming steps.

**Comment by mathieuboudreau** [comment]
Great, thanks Agah! 

Let's go with `qsm_sb.m` for the model file name then, to keep with the naming convention we have for qMT. We can make a note of the alternative name (TVSB) in the file header.

**Comment by agahkarakuzu** [comment]
Merged #266. Please see #208 regarding preprocessing.
