### ISSUE TITLE
Saved ROI should be loadable as a Mask into models

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#241]
Currently, saved ROIs are store a variable called Mask which is a 1x1 cell of a struct with two properties: vol and color. Because of this, the saved roi *.mat cannot be loaded as a Mask for the model.

**Comment by TommyBoshkovski** [comment]
Hi @mathieuboudreau, I already handled this in the ROI tool. I removed the vol and color fields from the ROI cell array. But we are saving the whole ROI cell array as a mat,  do you think we should combine the saved ROIs when loading them as a mask or should we save each element (ROI) from the cell array as a separate mat file?

**Comment by mathieuboudreau** [comment]
> do you think we should combine the saved ROIs when loading them as a mask or should we save each element (ROI) from the cell array as a separate mat file?

I think if the user tries to load the ROI set as a mask, they would assumed that all ROI are combined to create a single mask (that's what I would want anyways). Maybe @HarrisNami could chime in, since he's the user who's used ROI tools in qMRLab the most.

Do you have a preference @TommyBoshkovski ? What behaviour would you want if you were using this feature?

**Comment by HarrisNami** [comment]
I guess loading them in a single mask so all the ROI are loaded at the same time is more efficient and practical. Personally for me if I am looking at one ROI I would only like that one to be there, but since the tool shows only one ROI at a time anyway that isn't as a big of a deal.

**Comment by tanguyduval** [comment]
solved in #296
