### ISSUE TITLE
[BUG] Cannot plot histogram when 3D (or 4D) masks are loaded in model

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#242]
Encountered while trying to plot the demo NODDI data, errors in line 597:

https://github.com/neuropoly/qMRLab/blob/7f51063120171afe87e03717bc7aa398b427426e/qMRLab.m#L589-L599

This happens because the data to analysed using a histogram, `Map`, is the 2D image currently plotted in the GUI, whereas the Mask, `Data.(Model).Mask`, is the entire mask. The mask needs to be sliced to match the volume in display prior to masked the `Map`: e.g. using the slice, volume, and view information set in the GUI.

**Comment by tanguyduval** [comment]
Solved in #296
