### ISSUE TITLE
CLI Template for MCR

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#252]
On the `bids` branch, I've started working on a main entry function for Matlab Compile Runtime Engine. In the meantime I will be compiling all the fit functions with their dependencies (R2017b, Ubuntu 16.04). I am writing a script to automatize compiling too. Ideally, we will compile library after each release and host compiled library on OSF to save GitHub space. 

The purpose of this effort is to execute fitting functions (at least for now) on a docker container that can be also mapped on HPC clusters. To this end, I created a new docker composition:

```
  qMRlab/docker

     /MCR
        Dockerfile

     /OctJN
        Dockerfile

   /docker-compose.yml
```

The env defined in the Dockerfile under OctJN creates an image which is currently hosted on DockerHub with the [neuropoly/qmrlab tag](https://hub.docker.com/r/neuropoly/qmrlab/). Running this image, one can start a Jupyter Notebook (JN) that can run qMRLab via Octave kernel. Details can be found [here](https://hub.docker.com/r/neuropoly/qmrlab/).

**Example use case for OctJN**
 
Imagine you have a repository with either some Jupyter Notebooks or some .m code that uses qMRLab. You create a Dockerfile that contains following line only, then push it to your repo:
`
FROM neuropoly/qmrlab  `

Now you can point BinderHub to this repo. It will allow you to run your JN or execute your .m on a JupyterHub session. 

**Example use case for MCR**

MCR environment is much more lightweight than the OctJN. This makes it more desirable for computational environments where built Docker images are not kept for a long time. More importantly, with MCR, qMRLab modules can be evoked from system command-line with a desired template using boutiques, then can be submitted to HPC. Also keep in mind that Matlab works way more efficient than Octave, especially when it comes to heavy optimization tasks. 

Having this functionality will open the way for integrating qMRLab to Compute Canada or Open Neuro. 

**Deciding on a CLI template**

I started writing the `qMRcli` script. To keep commandline calls concise, I decided following prototype:

`void qMRcli(inputFolder, jsonOpt, outputFolder)`

In this scenario, user places a json file under the folder that contains raw qMR data. For `mt_sat` this json looks like this:

```
{
        "mt_sat": {
                "MTw": {
                        "Filename": "MTw.nii.gz",
                        "FlipAngle": 6,
                        "RepetitionTime": 0.028
                },
                "PDw": {
                        "Filename": "PDw.nii.gz",
                        "FlipAngle": 6,
                        "RepetitionTime": 0.028
                },
                "T1w": {
                        "Filename": "T1w.nii.gz",
                        "FlipAngle": 20,
                        "RepetitionTime": 0.028
                }
        }
}
```

Assuming that json is at the same folder with the data, and the output will be saved there too, command will look like:

`myComputer:~$ qMRcli mtsat_data_folder`

A json file that matches file- and fieldnames, includes the model name and the neccesary parameters. qMRcli then can easily perform the fitting. 

Without a standard like BIDS, users need to create these jsonOpts manually, or through the [website](tommyboshkovski.github.io/json/) @TommyBoshkovski created.  Having qMR descriptions in BIDS, we can just check out the `'anat'`  folder to generate jsonOpts automatically. 

**Please give feedback** on this CLI template that I am planning to proceed with.

**Comment by tanguyduval** [comment]
@agahkarakuzu this looks very promising.

You do not need to compile each model individually for the MCR. When compiling `qMRcli` add all the models files inside. Then when calling qMRcli you will be able to create an object of any Model based on the model name given as input.

In a next step, that would be good to be able to add a saved qMRLab Model object as input (in .json format). That way, we could use model options.

Also, We might want to use the qMRcli for simulation purposes in the future, so I would name it `qMRfit`

Good luck!

**Comment by agahkarakuzu** [comment]
@tanguyduval Thanks for the feedback!

I was planning to compile one by one to make it modular, so that  Python wrapper can be modular (from qMRLab import xxx). Not sure if it is going to work the way I thought of, but compiling all together is definitely an option.  

Converting a saved qMRLab object to a json should be quite straightforward (hope wont regret saying this :D ) as it is already a struct. 

I think splitting `qMRcli` into `qMRfit` and `qMRsim ` is a good idea.

**Comment by mathieuboudreau** [comment]
I'm going to go over this right now, but one point that I'm quite strongly opinioned on is that the CLI commands should be all lowercase, as this is the convention for the majority of Unix-style CLI commands, and it's easier to "tab" (`qmrfit` instead of `qMRfit`). 😅

**Comment by mathieuboudreau** [comment]
But if Nikola/Agah are also strongly opinionated about leaving the "MR" uppercase for "branding", then I'll let it go, I just think it'll be a nuissance for the users. lol

**Comment by agahkarakuzu** [comment]
@mathieuboudreau both works fine for me. At the end of the day boutiques will do the function call with a descriptor and  an invocation json. For example this is how mt_sat_batch.sh is described as a command line:

`"command-line": "/home/agahkarakuzu/R2016b_lnx/Standalone/for_redistribution_files_only/run_mt_sat_batch.sh /usr/local/MATLAB/MATLAB_Runtime/v91 [PARAM1] [PARAM2] [OUTPUT1]"`

which is to be called via boutiques as:

`bosh exec launch mt_sat_batch.json inp.json -v (volume to be mounted on docker sandbox)`

I will play around with boutiques more to see if I can make it more concise and maybe can get rid of json extension declarations. 

Yet I agree, `qmrfit` and `qmrsim` it is.

**Comment by agahkarakuzu** [comment]
> Just to clarify, MCR = Matlab Compiled Runtime and OctJN = Octave Jupyter Notebook?

@mathieuboudreau yes it is. 

> Will you need to have the dockerfile that you created for your new notebooks saved on your Github repo to work?

Dockerfile is not neccesary. After we push these to the DockerHub, people can use neuropoly/qmrlab as the base image for their Docker env. and add anything they want on top of that. These dockerfiles will be hosted on our repo so we can configure automated builds.

**Comment by agahkarakuzu** [comment]
JSON file should be in harmony with the way people keep their source data in the folder. Right now `qmrfit.m` is able to distinguish these two cases to operate correctly: 

**Flat case**

 For qData that can be stored after collapsing all quantitative dimensions into one entity such as `IRData.mat`, all parameters should be passed as a vector. If this is the case JSON will look like:

```
{
        "inversion_recovery": {
                "IRData": {
                        "Filename": "IRData.mat",
                        "InversionTime": [350, 500, 650, 800, 950, 1100, 1250, 1400, 1700]

                },
                
                "Mask": {
                        "Filename": "Mask.mat"


                }


        }
}

``` 

**Nested case**

If each member of the quantitative dimension is kept separately, then the main quantitative data field will have subfields. It will look like (fake BIDS :) ):

``` 
{
        "inversion_recovery": {
                "IRData": {
                            "inv1":{
                              "Filename": "Sub-01_qClass-11_inv-1.nii",
                              "InversionTime": 350
                            },
                            "inv2":{
                              "Filename": "Sub-01_qClass-11_inv-2.nii",
                              "InversionTime": 400
                            },
                            "inv3":{
                              "Filename": .nii, .nii.gz or .mat "Sub-01_qClass-11_inv-3.nii",
                              "InversionTime": 450
                            },
                            "inv4":{
                              "Filename": "Sub-01_qClass-11_inv-3.nii",
                              "InversionTime": 500
                            },
                            "inv5":{
                              "Filename": "Sub-01_qClass-11_inv-5.nii",
                              "InversionTime": 550
                            }
                },
                "Mask": {
                        "Filename": "Mask.nii"


                }


        }
}

``` 

All data to be loaded can have any of `.nii, .nii.gz or .mat ` format, `qmrfit.m` is adaptive to that. 

Please let me know if you think there are more cases to add.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu These are the two most common cases I encountered during my PhD. Of course I could think up of some odd-ball cases (e.g. qMT with a VFA T1 map, but re-using the no-MT qMT measurements as one of the two VFA measurements to save some time), but you shouldn't worry about those custom cases for now I think.

**Comment by agahkarakuzu** [comment]
https://github.com/qMRLab/qMRflow
https://github.com/qMRLab/qMRWrappers
