### ISSUE TITLE
AWS Free tier limit

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#261]
Just a heads up that I got an alert from Amazon Web Services that we're at 85% of our storage PUT limit for the month of August:

![aws](https://user-images.githubusercontent.com/1421029/44169033-971d5800-a0a9-11e8-9dc0-0b198af16375.png)

We use this service to store the coverage tests prior to recombining them and sending them to Coveralls.io at the final Travis test stage. 

It won't be a huge issue if we hit it, however the Travis tests will fail continuously if we do.

Things that can be done to reduce usage of this service:

1 - Don't push every single commit when you commit them – wait until you have several and push them together (only the most recent one will run a Travis test in that case).

2 - If you do push a commit, but don't need to see if it passes the Travis test, simply go on the Travis page and cancel the build (you'll need an account for this, I think either @agahkarakuzu or @tanguyduval can add members).

If we do hit this limit, I (or @agahkarakuzu ?)  might create another AWS account as a backup in case this happens so that we can at least last until the end of the month, and then we should be more conservative in the future.

(@agahkarakuzu @ileppe @tanguyduval @TommyBoshkovski)

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I just had to push one bcz Matlab license service connection at Poly keeps being lost today, I will keep working on my mac at home. Yet, I canceled build :+1:  Thx for the heads up. 

These days I am all about creating new accounts to take advantage of promotions, so sure I can create an AWS account to.

**Comment by mathieuboudreau** [comment]
Looks like we already beyond our limit, but I'm only going to get charged a penny per 2000 extra request, so I guess I'll eat it for this month 😅

![aws](https://user-images.githubusercontent.com/1421029/44597192-35de3e80-a7a5-11e8-97e2-cf11d90aa31f.png)
