### ISSUE TITLE
What's hogging time?

### ISSUE THREAD

**Issue by ileppe** [qMRLab/qMRLab#285]
After waiting way to looong (as was noticed here #221) to fit some high-res VFA data, I had a look at what's taking so much time, .
From the profiler in matlab (nifty tool I didn't know about), it looks like most of the time is spent saving temporary data to the temp file:
![qmrlab](https://user-images.githubusercontent.com/28764708/47677845-a2efc500-db96-11e8-8e8d-433476db9add.png)

I think we are saving after every 20th voxel, maybe we should try to increase this or find some other way to store the data.

**Comment by mathieuboudreau** [comment]
Wow! Thanks for looking into this and finding the problem @ileppe !!

Ah ha - yet another feature that was implemented for the qMT tools. Useful for slow models, not so much for fast ones.

We could do a few things:

* Remove this feature altogether for certain models by creating a flag in the model (devs would be responsible to decide which models should have it or not, by doing a test like you did).
* Give the option in the GUI/CLI to save temp, and if so, at what frequency.

As a short term solution, I'd rather do point #1, as it'll be quicker, won't clutter the GUI, and makes it harder for users to "make a mistake" and set a high frequency saving causing huge slow downs in processing time.

How do you feel about it?

**Comment by agahkarakuzu** [comment]
@ileppe thank you for the diagnosis! 

@mathieuboudreau I totally agree  with you. If saving data to a static memory unit back and forth takes up 60 times more than the process itself, we can definitely skip this for that method. We can repeat the profiler for all the methods and see when saving actually becomes purposeful. I think we can set some ratio thresholds to that end. 

Such read/write operations are also confounding parallelization, which may be of a future concern.

**Comment by spinicist** [comment]
Well, I guess that explains https://github.com/qMRLab/qMRLab/issues/221

**Comment by tanguyduval** [comment]
@mathieuboudreau <https://github.com/mathieuboudreau> why not simply saving
a temp file every 5min instead? there is already a time counter in FitData,
we could use it.

@ileppe <https://github.com/ileppe> great job with the profiling

**Comment by mathieuboudreau** [comment]
@tanguyduval That's another option! I don't have a strong opinion between that or setting a flag as I mention above.

**Comment by ileppe** [comment]
Ok, I tested with VFA and qMT_spgr and it seems to work, saving every 5min, based on timer. Please see:

https://github.com/qMRLab/qMRLab/blob/6beacf4c494621d0e7a9df39510780b4d24ee705/src/Common/FitData.m#L130

**Comment by ileppe** [comment]
Related issue and I think we've talked about this before, but the printing out of the same warning for every voxel is also a bit tedious and probably wasting time (for e.g. qMT_spgr)

https://github.com/qMRLab/qMRLab/blob/6beacf4c494621d0e7a9df39510780b4d24ee705/src/Models/Magnetization_transfer/qmt_spgr.m#L273-L275

We could make it show only once at the beginning?

**Comment by mathieuboudreau** [comment]
@ileppe absolutely! Printing voxel updates at every voxel for is also a slow down, which is partly why I removed them for CLI functionality (800fd6f referenced in #278). Yet another feature that was useful for the initial Sled & Pike qMT (slow method) that should not have been implemented for all methods – thanks for noting that one!

**Comment by mathieuboudreau** [comment]
>Ok, I tested with VFA and qMT_spgr and it seems to work, saving every 5min, based on timer. Please see:

@ileppe If you think this fix sufficiently resolves your concerns for the moment, I'd say go ahead and make a pull request so that we can all benefit from the time saving 😅
