### ISSUE TITLE
OSF Data versions and `onlineData_url` links 

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#288]
```diff
- `b1_dam.MRIinputs = {'SF60','SF120'}`
- `b1_dam.Prot = []`
- `b1_dam.onlineData_url = https://osf.io/8ypzw/download`
+ % Changes to the b1_dam, patched, version 2.0.12 --> 2.0.13 
+ `b1_dam.MRIinputs = {'SFalpha','SF2alpha'}`
+`b1_dam.Prot = struct('Alpha',struct('Format',{'FlipAngle'},'Mat',60));`
+`b1_dam.onlineData_url = https://osf.io/8ypzw/download`
```
**Problem**

After these changes, Travis test won't pass given that qMRGenBatch will be looking for `SFalpha.nii.gz` and `SF2alpha.nii.gz`, but the OSF data will be still containing `SF60.nii.gz` and `SF120.nii.gz`.

If I update the `b1_dam` OSF data, then people who have qMRLab version < `2.0.13` won't be able use qMRGenBatch or `DownloadExample` smoothly. Because `https://osf.io/8ypzw/download` is always pointing to the latest version of the data on OSF (this is the link in all former versions we assign to the `onlineData_url` attribute). 

**Reminder**
 
OSF allows us to freeze data version in download links such as `https://osf.io/8ypzw/download?version=2`, which we should have been using so far instead of using the `latest`. 

**Solution**

I will upload `b1_dam_v2_0_13/b1_dam.zip` (contains `SFalpha.nii.gz` and `SF2alpha.nii.gz`)  to OSF and update `b1_dam.onlineData_url` with the link pointing to (the version-1 of)  that file. This way:

i)   Ppl using qMRLab < 2.0.13 will still be able run examples smoothly 
ii)  Travis will pass for qMRLab == 2.0.13
iii) Ppl using qMRLab >= 2.0.13 will be able to run examples smoothly 

In addition to this, I will add version tags to the `onlineData_url` attributes of all models. This way, if we need to change something in the models that requires renaming respective OSF files, we won't break retro-compatibility.

**Comment by mathieuboudreau** [comment]
I think that works. So should we change the links to all other methods so that the point to a specific version # right now?

@jcohenadad @tanguyduval how do you feel about this proposed solution by @agahkarakuzu ? I don't know if this will necessarilly be a problem that might occur frequently (model parameter/input names should and have been defined in a general way from their creation; Double Angle B1 mapping seems to be an odd case that slipped through the cracks; only dealing with FA = 60 and 120 was much to specific from the beginning)

**Comment by tanguyduval** [comment]
I don't have strong feelings about this issue. Creating new zip files if the filenames changed is not a big deal. Agah solution looks good

**Comment by agahkarakuzu** [comment]
Thanks @tanguyduval, fa297c401759c7c4d7efd0cfb152ead7ded1a288 seems doing good. I will close this issue upon merging #290
