### ISSUE TITLE
Model.Prot.DiffusionData

### ISSUE THREAD

**Issue by Davi1990** [qMRLab/qMRLab#299]
Dear all, 

I'm trying to use NODDI model for fitting multi-shell DWI. Anyway I'm not able to figure out how can I get the information to put in the model (Model.Prot.DiffusionData.mat)

The first three rows should be the bvecs (Gx, Gy, Gz) while the the fouth row (  Gnorm (T/m)) should be the vals even though the values in the example_nodi dataset are really low so I'm not sure if I need to convert them. 
Moreover I don't know how to get the last 3 rows which are: 
- Delta (s)         Diffusion separation
- delta (s)         Diffusion duration
- TE (s)            Echo time

Could you please help me with that? 

Thanks 

Dave

**Comment by tanguyduval** [comment]
@Davi1990 Thank you for asking your question

Diffusion separation and duration are necessary for experiments acquired with some very large bvalues (i.e. >5000 s/mm^2, were diffusion is non-Gaussian).
See http://mriquestions.com/what-is-the-b-value.html

**On a clinical scanner**, you can convert bval/bvec files using the following Matlab command:
```matlab
bvecfile = 'dwi.bvec';
bvalfile = 'dwi.bval';
Gmax = 40; % (mT/m)
scd_schemefile_FSLconvert(bvalfile, bvecfile, 40, 'scheme.txt')
```

That will create a file `scheme.txt` that you can load in the Options Panel.

Use the `Plot fit` button to check the consistency of your data. You should get something similar to this:
https://qmrlab.readthedocs.io/en/master/noddi_batch.html#9

Please let me know if everything works fine now.
Best,
Tanguy

**Comment by Davi1990** [comment]
Hi Tanguy, 

thanks for your response! I've used the scd_schemefile_FSLconvert function but I got this error message:

Error using exist
The first input to exist must be a string scalar or character vector.

Error in txt2mat (line 702)
elseif exist(ffn,'dir') == 7

Error in scd_schemefile_FSLconvert (line 19)
bval = txt2mat(bvalfile);

As for the Diffusion separation and duration I'm not sure on the acquisition parameters because I'm working with the HCP data (subjects 100307). 

Thanks

Davide

**Comment by tanguyduval** [comment]
Hi Dave,

it seems like you did not enter a filename but a variable for the inputs  bvecfile and bvalfile.
Please enter the fullpath:
```matlab
bvecfile = 'pathtodata/dwi.bvec';
bvalfile = 'pathtodata/dwi.bval';
```

A file `scheme.txt` will be created in the current working directory (run the command `pwd` to know the working directory).

Best,
Tanguy

**Comment by tanguyduval** [comment]
Concerning the diffusion separation and duration, the HCP data have max bvalue of 3000s/mm2. So you can reasonably use the command `scd_schemefile_FSLconvert(bvalfile, bvecfile, 40, 'scheme.txt')
` and it will compute automatically your duration and separation in the scheme file.
Best

**Comment by Davi1990** [comment]
Hi Tanguy,

thanks for your help. As for the bvec, bval I've actually load the values so I ended up with two matrices: 

bval: 1x288
bvec: 3x288

So I don't know what I might be the problem 

Thanks

Davide

**Comment by tanguyduval** [comment]
Well, that is exactly the issue, do NOT use your variables, instead, you should inform the bvec/bval files directly.
I converted the bvec/bval files for the subject. Find the scheme.txt attached:
[scheme.txt](https://github.com/qMRLab/qMRLab/files/2724934/scheme.txt)

**Comment by agahkarakuzu** [comment]
> @tanguyduval Thanks for clarifying when and how to use the duration and separation values. Is this documented somewhere? Maybe we could include this information in a mouse hover or ? button.

We can use [tooltips](https://github.com/qMRLab/qMRLab/wiki/Guideline:-GUI#adding-tool-tips-for-the-options-panel] for that, adding it to my to-do list for today.

**Comment by agahkarakuzu** [comment]
I've added mouse hover tooltip for the `DiffusionData` table of the `noddi`, available on [`tooltips`](https://github.com/qMRLab/qMRLab/tree/tooltips). In addition to the explanations of params, I added referrals to this issue and to readthedocs (for now). As @mathieuboudreau  previously suggested #174, we can create a FAQ section and move this issue there, to be discussed in the next meeting.   

P.S. @Davi1990 , [here is another source](https://blog.ismrm.org/2017/06/06/dwe-part-2/) by @TommyBoshkovski  to understand Delta and delta without equations. Thank you for reaching out!

**Comment by tanguyduval** [comment]
Many thanks @agahkarakuzu !

**Comment by Davi1990** [comment]
Hi Tanguy and Agah, 

I've worked on the HCP dataset following your suggestions (thanks again). 
First of all I was able to get all the ouputs but unfortunately they are completely empty (See attached). Any tips? 

Moreover, I'm running a NODDI model to get the fiber volume fraction (FVF) in order to compute the g-ratio. My question is which one among the outputs (di, ficvf, fiso, fr etc.) is the FVF map? 

Thanks again

D
[diso.nii.gz](https://github.com/qMRLab/qMRLab/files/2729754/diso.nii.gz)
[ficvf.nii.gz](https://github.com/qMRLab/qMRLab/files/2729755/ficvf.nii.gz)
[fiso.nii.gz](https://github.com/qMRLab/qMRLab/files/2729756/fiso.nii.gz)

[fr.nii.gz](https://github.com/qMRLab/qMRLab/files/2729757/fr.nii.gz)
[kappa.nii.gz](https://github.com/qMRLab/qMRLab/files/2729758/kappa.nii.gz)
[ObjectiveFun.nii.gz](https://github.com/qMRLab/qMRLab/files/2729759/ObjectiveFun.nii.gz)
[ODI.nii.gz](https://github.com/qMRLab/qMRLab/files/2729760/ODI.nii.gz)
[phi.nii.gz](https://github.com/qMRLab/qMRLab/files/2729761/phi.nii.gz)

[theta.nii.gz](https://github.com/qMRLab/qMRLab/files/2729762/theta.nii.gz)
[b0.nii.gz](https://github.com/qMRLab/qMRLab/files/2729763/b0.nii.gz)
[di.nii.gz](https://github.com/qMRLab/qMRLab/files/2729764/di.nii.gz)

**Comment by agahkarakuzu** [comment]
Hi @Davi1990 is it possible for you to share your source files and protocol (`noddi.qmrlab.mat`) with us, so that we can try to reproduce these outputs and better diagnose what's going on. 

If you are using command line, can you please share your code with  (gist)[https://gist.github.com/]?

**Comment by Davi1990** [comment]
Hi @agahkarakuzu! Yes, sure. I've sent an email to you with both the raw data (Diffusion, Mask, bvecs and bvals) and the output files as well as the protocol. 

As for the code I've tried with the GUI and the command line but I got pretty much the same output. Anyway here is the code

<script src="https://gist.github.com/Davi1990/c2136a5c30cd0b6cb9fabbdd155011a5.js"></script>

Thanks again for all your support 

Davide

**Comment by tanguyduval** [comment]
@Davi1990 The problem is the absence of b=0 data... The lowest bvalue is 5 s/mm2 (which is nearly 0).
A simple solution is to set b=5 to b=0... Manuallly in the GUI or with the CLI. 
See the full code below (extract data.nii.gz --> data.nii). Adapt from the example obtained using `qMRusage(noddi)`

```matlab
%% CHANGE THIS LINE!
cd('pathtoHCPdata')

%% ----------------------------------------------------------------------------
%% Fit data (see usage example of the fit method: >> qMRusage(noddi) )
%% ----------------------------------------------------------------------------

Model = noddi;

%% LOAD DATA (extact data.nii.gz --> data.nii for faster processing)
data.DiffusionData = load_nii_data('data.nii');
data.Mask = load_nii_data('nodif_brain_mask.nii.gz');

%% Convert bvec/bval to scheme
bvecfile = 'bvecs';
bvalfile = 'bvals';
Gmax = 40; % (mT/m)
scd_schemefile_FSLconvert(bvalfile, bvecfile, 40, 'scheme.txt');

%% Load Protocol
Model.Prot.DiffusionData.Mat = txt2mat('scheme.txt');

%% FIT A SINGLE VOXEL
% Specific voxel:         datavox = extractvoxel(data,voxel);
% Interactive selection:  datavox = extractvoxel(data);
voxel       = round(size(data.DiffusionData(:,:,:,1))/2); % pick FOV center
datavox     = extractvoxel(data,voxel);
FitResults  = Model.fit(datavox);

%% ERROR!! No b=0 !!
% set very low bvalue (G < 2 mT/m) to 0
Model.Prot.DiffusionData.Mat(Model.Prot.DiffusionData.Mat(:,4)<0.002,4)=0;

%% Redo FIT A SINGLE VOXEL
FitResults  = Model.fit(datavox);
figure;
Model.plotModel(FitResults, datavox); % plot fit results

%% FIT all voxels
FitResults = FitData(data,Model,1);
% SAVE results to NIFTI
FitResultsSave_nii(FitResults,'data.nii'); % use header from 'DiffusionData.nii.gz'
```

**Comment by tanguyduval** [comment]
TODO:
- [ ] allow bvec/bval files in DTI and NODDI
- [ ] Check if no b=0

**Comment by agahkarakuzu** [comment]
This issue was moved to https://forum.qmrlab.org/t/model-prot-diffusiondata/32
