### ISSUE TITLE
Filtering 

### ISSUE THREAD

**Issue by ileppe** [qMRLab/qMRLab#303]
As discussed in #135, we would like to have the ability to filter/smooth any image (e.g. B1map or B0map).
As part of adding a new model, this is the 1st step, getting it approved by the team: @agahkarakuzu @mathieuboudreau!

The suggestion is: 
  -  to have an abstract FilterClass, whose methods/properties can be inherited by any Model wishing to use that functionality (e.g. B1map inherits from AbstractModel and FilterClass)
 - add a `filter_map` Model that inherits from AbstractModel and FilterClass (FilterClass cannot be itself a model due to inheritance issues)
 - add the FilterClass to all B1mapping and B0mapping models for now. Will require some extra handling for other models if there's overlap (i.e. for example, the parent class' buttons override those of the child class)
 - available filtering/smoothing options
     - spline (2D, 3D)
     - gaussian (2D, 3D)
     - polynomial (2D, (3D in development))
     - media (2D, 3D)

Checklist of wiki guidelines that I still need to take care of:
   - [x] 2. help commands
   - [x] 3. link to sample data
   - [x] 7. control batch generation
   - [x] 8. control GUI
   - [x] 9. save static object

I'm currently on the 'b1_filter' branch if you want to take a look.

**Comment by agahkarakuzu** [comment]
@ileppe if you have completed this list, can you cross out the items and close this issue (#317)? Thanks 🎆
