### ISSUE TITLE
Complete community profile checklist

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#306]
See here: https://github.com/qMRLab/qMRLab/community

Missing items

* [x] Code of conduct
* [x] Contributing
* [x] Issue templates
* [x] Pull request template

Agah suggested @emdupre's tedana's repo for templates ideas: https://github.com/ME-ICA/tedana

**Comment by agahkarakuzu** [comment]
@mathieuboudreau 0967127e5ce2a13f60af8703108aa9c368c7a94a should work (based on your `idea_pitches` repo, this) I guess?

**Comment by agahkarakuzu** [comment]
Closed #321.

**Comment by emdupre** [comment]
Amazing !! :tada::sparkles::tada:

**Comment by mathieuboudreau** [comment]
@agahkarakuzu any clue why in the settings page, the Contributing and PR template haven't registered?

<img width="758" alt="Capture d’écran 2019-04-09 à 16 09 34" src="https://user-images.githubusercontent.com/1421029/55826150-eead7f80-5ae1-11e9-8040-021d2c9dedb8.png">

**Comment by agahkarakuzu** [comment]
@mathieuboudreau interesting, it can hyperlink to the COC, but does not give us a green check for that. As for PR template, I will fix it in my next PR.

**Comment by agahkarakuzu** [comment]
All set (COC is set as well, but it likes it orange).

![image](https://user-images.githubusercontent.com/9632322/55845694-f20c2f80-5b10-11e9-98ad-90463dbe8d0b.png)

**Comment by emdupre** [comment]
Yeah, now that you mentioned it I checked tedana's and we're orange too. I'll see if I can find an example of all greens...
