### ISSUE TITLE
Dependency graph

### ISSUE THREAD

**Issue by notZaki** [qMRLab/qMRLab#313]
I generated [this dependency graph](https://user-images.githubusercontent.com/9019681/53364150-2e425280-390c-11e9-8ce1-ce4a0d0678a8.png) while trying to get an idea of how different functions were connected.
Thought I'd share it in case anyone else finds it useful, even though some parts are congested.

It currently ignores local functions because it's possible for different local functions to have the same name, and that's too much of a hassle to sort out.

**Comment by mathieuboudreau** [comment]
Cool!! Is that made with a tool on MATLAB? What version are you using?

**Comment by mathieuboudreau** [comment]
We could probably add that to the wiki, and updated it with release versions. @agahkarakuzu what do you think?

**Comment by notZaki** [comment]
It's using [GraphViz](https://www.graphviz.org/) to make the figure, but everything is done through a MATLAB function. 
It's based on [M2HTML](https://www.artefact.tk/software/matlab/m2html/) which I've modified for documenting my own code. 

The practical application is to have something simpler, like the figure below, on a webpage where clicking on any of the function names will open a new page showing the function description and source code.  
![graph](https://user-images.githubusercontent.com/9019681/53364988-123fb080-390e-11e9-9620-1f05dca91713.png)

**Comment by agahkarakuzu** [comment]
@mathieuboudreau we can use Sphinx to automatically generate this. We can actually dedicate a Developer section for this on ReadTheDocs. 

On the other hand, semantics of the above graph is a bit puzzling. Yet, it is still useful. For example, `vfa_t1` does not point to `checkanteriorver`, reminded me to ask you about incrementing from 2.0.13 to 2.0.14 after  #314. Given that `voxelwise` property has changed and also the implementation.

**Comment by mathieuboudreau** [comment]
>reminded me to ask you about incrementing from 2.0.13 to 2.0.14 after #314. Given that `voxelwise` property has changed and also the implementation.

That version numbering is only for patches (we really need to consolidate this, or rename that version number). Even if `voxelwise` changed, because the Travis test and manual GUI tests did not fail, no patch was needed, so no need to increment that version number or implement a patch (which is where `checkanteriorover` would get called).

**Comment by notZaki** [comment]
I'll close the issue since it was only meant to share the graph.
I was hoping it would look like an umbrella. 
It kinda does if you look at it sideways, I guess.
