### ISSUE TITLE
Saving Octave provenance

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#334]
I run into this issue for `qmt_sirfse` [see failed Travis build](https://travis-ci.org/qMRLab/qMRLab/jobs/518095284). I completed a full fitting for this model on Octave; however, most likely due to version differences between packages (Travis Octave vs my Octave), difference for `M0f` was higher than 5%.  

I will downgrade my package versions to see if it is going to resolve the issue... I've uploaded `noddi` as well, if these guys are passing, `unittest_assertions` will be ready to be merged. 

Important: We should consider saving Octave & Octave package versions with `FitResults`. Same goes for MATLAB, we should better save MATLAB version and OS type. 

## Specifications

* Octave on my (18.04) machine:
     * Version: 4.2.2
     * image: 2.10.0
     * io: 2.4.12 
     * optim: 1.5.3
     * stats: 1.4.0 
     * struct: 1.0.15 

* Octave on TRAVIS (16.04):
     * Version: 4.2.2
     * image: 2.6.2
     * io: 2.4.10 
     * optim: 1.5.2
     * stats: 1.3.0 
     * struct: 1.0.14

**Comment by mathieuboudreau** [comment]
You're not running Octave through a docker image on your local? ;)

Great work Agah!

**Comment by agahkarakuzu** [comment]
I don't know where my local is anymore :D

**Comment by agahkarakuzu** [comment]
Provenance issue has been resolved 1cc26f7719900004b108ce41d9ca7ce268694596.

But there is something fishy with TRAVIS about these unit test assertions. After I deleted cache for that branch, behavior changed. Some of the tests failing due to 5% threshold are passing on my computers...

Closing this issue.
