### ISSUE TITLE
Experiment: Cleaning blob references that take up space 

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#336]
Below are the steps I followed. 

Sort 10 blobs that take up the much of the space: 
```
git verify-pack -v .git/objects/pack/*.idx | sort -k 3 -n | tail -10
```
Producing the reference list of:

```
c74571f3ce3048c3750d1ee151d49ea24107506e blob   12583264 9358991 322628979
182dfe17e0ad288020038376e4c44098f31b442e blob   12884016 12820266 381690934
941d178e3a24afa9d6fb0f21b7a1cf25da59cf42 blob   15445152 7552191 331988094
1775cf919cb02ef514f7b184d34933054d7caf7d blob   16627462 2994388 22588035
2cef77d4c460ba178970ed3616edb1410b5a3add blob   17520083 17506480 287642449
2c9fba09b42a0458c0de72edb7acaaa4cf1a5ea0 blob   23885450 23519683 211355482 1 ad96cf17c4c56fdf5c70ba2e068bf6654cb9955a
e0e6df0ad3d3733689504058f78cdb17fcce8de0 blob   26542432 7727459 353265419
62779cd736c3c35cda251cc2c84e7cd5a81dfe7c blob   26771793 26779973 34361036
ad96cf17c4c56fdf5c70ba2e068bf6654cb9955a blob   33467548 32499101 178856381
0c9c1ffffdf3ba4e13bf1968f3fbae5eadb240e2 blob   54360792 54135443 94121912
```

When inspected one by one, these are corresponding to: 

```
0c9c1ffffdf3ba4e13bf1968f3fbae5eadb240e2 Data/NODDI_DTI_demo/DifffusionData.nii.gz
ad96cf17c4c56fdf5c70ba2e068bf6654cb9955a ISMRM-qMTLab.pptx
62779cd736c3c35cda251cc2c84e7cd5a81dfe7c Data/CHARMED_demo/DiffusionData.nii.gz
e0e6df0ad3d3733689504058f78cdb17fcce8de0 Data/IR_demo/IRdata.nii
2c9fba09b42a0458c0de72edb7acaaa4cf1a5ea0 docs/qMTLab-Presentation.ppsx
1775cf919cb02ef514f7b184d34933054d7caf7d Models_Functions/MWF/met2_eva/data/logfile_multi_comp_fit
941d178e3a24afa9d6fb0f21b7a1cf25da59cf42 Data/NoiseLevel_demo/4Ddata.nii
182dfe17e0ad288020038376e4c44098f31b442e SIRFSE/FitResults/DemoFullBrain.mat
c74571f3ce3048c3750d1ee151d49ea24107506e Data/MTSAT_demo/FitResults/MTSAT.nii
```

These are just top 10, I am sure there is more. I will remove these blob references one by one to reduce our repo size from ~350MB to its actual size. As we don't want to time travel to any of these files at any given point, there is no harm doing this reference cleaning. 

Please let me know if you disagree @jcohenadad @mathieuboudreau @tanguyduval.

**Comment by mathieuboudreau** [comment]
I think I'm fine with this. Since this is the first time that we "rewrite history" this way, I'd recommend that you try this out on a fork of the repo and push it back to github first as a dry run.

**Comment by notZaki** [comment]
Since the git history will change if those blob references are removed, how will this be "merged" with the repo?

**Comment by mathieuboudreau** [comment]
Yup absolutely. @Agâh Karakuzu<mailto:agahkarakuzu@gmail.com> will people that have local clones be able to push back to github without issue if this is done?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by agahkarakuzu** [comment]
@notZaki  I am planning to use `git forget-blog` (https://github.com/nachoparker/git-forget-blob) approach. This procedure is not something to be merged similar to the branches we conventionally work on. 

I am aware of the risks and complexities (forced pushed, merges etc.) that may be involved in it. This is the reason why I will test it out on a fresh fork as @mathieuboudreau suggested. If you have a safer suggestion to do this, happy to hear that. 

@mathieuboudreau if we can get this done right, we will update developer notes and say that only clones from release `2.3.0` to be worked on. I am trying to deal with backlogged enhancements and finish them asap. We need a spring cleaning.

**Comment by mathieuboudreau** [comment]
>@mathieuboudreau if we can get this done right, we will update developer notes and say that only clones from release 2.3.0 to be worked on. I am trying to deal with backlogged enhancements and finish them asap. We need a spring cleaning.

What happens to all existing branches?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau they should be still OK, as references to the binary folders "are supposed to be" surgically removed. 

We can have all these questions answered in a fork. If anything, I think it is still useful to have a list of these references and find out what they are.

**Comment by notZaki** [comment]
It looks like `git forget-blog` uses `git filter-branch`. 
Maybe the [bfg repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) could be used instead---aside from being faster, it might simplify some steps. For example, it can delete the entire `Data` folder instead of having to reference each blob individually.

My understanding is that the branches in the repo will be fine, but everyone's local repo will have to be refreshed. So any local changes that were not pushed will be lost.

**Comment by agahkarakuzu** [comment]
@notZaki thanks, I will take a look at `bfg` as well! 

> My understanding is that the branches in the repo will be fine, but everyone's local repo will have to be refreshed. So any local changes that were not pushed will be lost.

This is my understanding as well, hope happens that way. I will simulate both scenarios on my fork.

**Comment by notZaki** [comment]
Here's a [list of large files](https://gist.github.com/notZaki/9edbb6c603acb3f0a808c5a8a0d508ac).
I pulled it by using the second answer from [this stackoverflow question](https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history)

Not sure if I did it correctly. I was expecting there to be more.

**Comment by agahkarakuzu** [comment]
Thanks @notZaki! 

Were you expecting more because the clone takes up ~490MB? The top 10 matches with what I've found, and the rest seems reasonable as well.  

I am giving `bfg` a stab now.

**Comment by notZaki** [comment]
Yea, I was expecting the ~490MB to be spread over a larger number of files, but I see now that the file sizes add up so it looks reasonable. 👍

**Comment by agahkarakuzu** [comment]
So, I tried `bfg` on a new fork `agahkarakuzu/qMRLab`. Before doing that I created two branches `foo1` and `foo2`. I comitted trivial changes in both branches, but pushed only `foo1` to the origin before doing `bfg`, whereas `foo2` remained as a local branch.

After `bfg` the size of the whole repo reduced down to `118MB` from `~490MB`. Then, I pushed `foo2` to the origin as well and created PR for both `foo` branches. Here are the PRs:

#### Foo1 
![image](https://user-images.githubusercontent.com/9632322/56056005-ff9c0200-5d28-11e9-9c57-21332b246780.png)

#### Foo2 

![image](https://user-images.githubusercontent.com/9632322/56056035-15a9c280-5d29-11e9-959d-67b9b9e4a667.png)

You can see the difference between # of files changed. Bottomline, it reduces the overall repo size as expected, do not break functionality, features improved on branches can be still merged, yet the history gets messy. 

I will leave this `agahkarakuzu/qMRLab` fork as an example of what might happen if someone would like to attempt this in feature. Until then, we will expect our users to use qMRLab as described in the documentation and our contributors (even though not necessary)  to sacrifice 500MB space from their HDD :) 

Thanks @mathieuboudreau and @notZaki for your remarks. 

Conclusion: 

* Do not `bfg` clean and rewrite history of `qMRLab/qMRLab` 
* Adjust git depths on CI service/docker configurations to 1 for efficiency.

**Comment by mathieuboudreau** [comment]
>Until then, we will expect our users to use qMRLab as described in the documentation and our contributors (even though not necessary) to sacrifice 500MB space from their HDD :)

Just to clarify, the users don't have to sacrifice 500Mb, they can simply clone the latest branch instead of the entire history, e.g.

`git clone --depth 1 --single-branch -b master https://github.com/qMRLab/qMRLab.git`

We could add this instruction/advice in the documentation

**Comment by notZaki** [comment]
Speaking of the master branch: here's a [list of large files on the current master](https://gist.github.com/notZaki/a52ba90289889f4c41bdc1e13a8f4485).

The gifs have a large file size because each frame was saved as a complete image. Their size can be reduced by a factor of ~4 by only saving the difference for each frame. Here's a [zip file](https://github.com/qMRLab/qMRLab/files/3074705/gifs.zip) containing the reduced gifs. 
Then again, is it possible to host these gifs externally to avoid having to include them in the repo?

**Comment by mathieuboudreau** [comment]
Nice!

@tanguyduval are those gifs for imTools3d really necessary?

@agahkarakuzu even though we likely aren't going to use the nuke button (`bfg`), we should still think about writting a Travis tests that verifies that no files were commited that have a size above a certain threshold (we can even make it an allowed failure, just something to warn us)

**Comment by tanguyduval** [comment]
Oups.. I guess you caught me 👮! 😉 
I added these GIFS with imtool3D PR. They are used in the autodoc:
https://qmrlab.readthedocs.io/en/master/gui_usage.html#data-viewer

If we zip those files, it will break sphinx compilation I guess..
Is this a big hassle to have these large GIFS? Another solution: make a nice video of the viewer that we publish on Youtube and embed in the doc

**Comment by tanguyduval** [comment]
Just found that these gif can be compressed individually by 80% using https://ezgif.com
![image](https://user-images.githubusercontent.com/7785316/56061274-44e02400-5d69-11e9-8f1f-1b25e86c4747.png)

**Comment by agahkarakuzu** [comment]
That website comes in handy for cropping gifs as well! Another option to upload GIFs to OSF and link from there.

**Comment by mathieuboudreau** [comment]
An alternative could be to host these types of resources (images, gifs) in another repo, or externally (i.e. OSF, Amazon AWS S3 like I do for my blogs).

**Comment by agahkarakuzu** [comment]
Thank you all for your inputs, I am closing this issue 🚀. 

Please see [this comment for a summary of this experiment](https://github.com/qMRLab/qMRLab/issues/336#issuecomment-482664858).
