### ISSUE TITLE
mrathon 2019 contributions

### ISSUE THREAD

**Issue by tanguyduval** [qMRLab/qMRLab#341]
Here are a couple of projects for:
  - Perfusion Module for DSC and DCE with @b3nbm @slevy #315 
  - Preprocessing of QSM by @jeremie-fouquet:
    * Add combine multi-echo preprocessing module
  - use VisualQC for MTsat by @agahkarakuzu and @raamana
  - T2, T2* offset simulator by @JoaoPeriquito #340
  - MonteCarlo Simulator by @yasuhik: https://github.com/Yasuhik/MonteCarlo_Diff

**Comment by tanguyduval** [comment]
@yasuhik is done. I'll integrate his repo through a copy into qMRLab/external

**Comment by agahkarakuzu** [comment]
Following up on MRathon efforts before I go to my :medal_military: :gun: :running_man: :small_airplane: :smile: 

@jeremie-fouquet how far are we from merging your changes? 

@b3nbm @slevy First off sorry that I could not make it to the OSIPI meeting on Friday, I was sick. I sent an email to ask attending remotely but could not hear back. Please bring me up to date if there are any decisions made during the meeting regarding qMRLab's (potential or current) involvement.

@b3nbm same question, how far do you think we are from merging your additions?

 @JoaoPeriquito, I created the branch for T2, so I will polish it and merge :) I would give heatmaps a shot if you could share your code with me. 

Version `2.4.0` will include all your contributions :rocket: 

First MRathon was a great ride, thank you all !

**Comment by jeremie-fouquet** [comment]
I hope to be able to push a debugged version by the end of this week.

**Comment by agahkarakuzu** [comment]
Many thanks to all contributors! These features will be available in `v2.4.0` 🚀
