### ISSUE TITLE
Loaded nifti files not displaying with correct value range in GUI

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#349]
## Expected Behavior
Nifti B1 map loaded should have values between 0.7 and 1.3 ish (e.g. filter_class)

## Current Behavior
Using the GUI, the values range from 0 to 4095.

## Possible Solution
In these lines here, replace `load_untouch_nii` with `load_nii_data`

https://github.com/qMRLab/qMRLab/blob/7f51063120171afe87e03717bc7aa398b427426e/src/Common/tools/LoadImage.m#L15-L23

## Steps to Reproduce
* Open qMRLab
* Select`filter_map` method
* Click **Download example**
* View the Raw image
* Click on a brain voxel and look at the value.

## Other information

I found out about this because the script generated by qMRgenBatch properly loaded the nifti file - but for that case, it uses `load_nii_data` explicitely, e.g. 

```matlab

%% III- FIT EXPERIMENTAL DATASET
%%       a- load experimental data 
%           |- filter_map object needs 2 data input(s) to be assigned:
%           |-   Raw
%           |-   Mask

data = struct();
% Raw.nii.gz contains [128  128   35] data.
data.Raw=double(load_nii_data('filter_map_data/Raw.nii.gz'));
% Mask.nii.gz contains [128  128   35] data.
data.Mask=double(load_nii_data('filter_map_data/Mask.nii.gz'));

```

Not sure if in the solution for this issue we need to convert to double like it's done there, maybe.

I've tagged a several of you as assignees since I'm not sure if your own models expect the nifti's to be loaded using the 0-4095 range; if so, we might need an additional option for certain model to switch between the two image reading modes.

**Comment by mathieuboudreau** [comment]
Not sure if the specific location that I mentionned is the source of the problem anymore, I tried fixing it temporarily in my branch this way and it didn't work, so maybe there's somewhere else.

@tanguyduval maybe your new viewer is the source of this problem.

**Comment by mathieuboudreau** [comment]
I think it is your viewer, as the data itself that's saved in the model seems to be in the correct range; it's just not displaying with the proper values.

**Comment by tanguyduval** [comment]
@mathieuboudreau This is the classical Nifti header `scl_slope` that is causing the error.
We have two options:
1. Load the Nifti in double and apply the slope immediately. 
Pros: prevent 
Cons: memory intensive due to the conversion of integers into double... Might crash on very large datasets.
2. Ask to the user whether we should apply the slope (if scl_slope is different to 1).
Pros: Would work in all cases
Cons: User might not understand this message. We need to document this 
3. Apply the slope to the viewer reported values.

I would go for option 2. WDYT?

**Comment by mathieuboudreau** [comment]
@tanguyduval How about a mix of both 1 and 2: automatically apply (or not?) the slope, and but keep an option somewhere available for the user to revert to the other way (or even better, to change their default behaviour for their qMRLab experience). As for the message, I myself don't fully understand what you mean by slope, so I would simplify the message/jargon to the user somehow if possible.
