### ISSUE TITLE
New user guide

### ISSUE THREAD

**Issue by zrazi** [qMRLab/qMRLab#369]
I have opened the qMRLab using Jupyter nb , but I am not sure how to actually run the code and study my images. Any help is appreciated.

**Comment by agahkarakuzu** [comment]
@zrazi have you seen our documentation? https://qmrlab.readthedocs.io/en/master/

qMRLab has a GUI that helps explore your outputs. If you don't have MATLAB, Dockerized version can also provide you with the GUI. 

Which model are you using?

**Comment by zrazi** [comment]
I have followed the tutorial that you posted a while ago and I'm not sure which model is it. I have access to the last version of Matlab and could open qMRLab and see the interface. But that was via the Citrix Receiver hosted by university and I though I may be better switching to the Python version. But not sure how to launch the interface from here
<img width="630" alt="1" src="https://user-images.githubusercontent.com/47364685/72107739-f82d7780-32ff-11ea-82e8-b63dbbef0daa.png">

**Comment by agahkarakuzu** [comment]
@zrazi https://github.com/qMRLab/doc_notebooks repository has a collection of notebooks that guides you through fitting data using the Jupyter Notebook interface. On an important note, qMRLab's GUI is not accessible through Python or Octave. However, you can make use of all the command line functions on Jupyter Notebooks with Octave kernel.

You can start by running [this notebook](https://github.com/qMRLab/doc_notebooks/blob/master/vfa_t1_notebook.ipynb) in your Jupyter Lab session. 

You can run the same notebook online by clicking the Binder badge at the top of the page of the respective documentation: https://qmrlab.readthedocs.io/en/master/vfa_t1_batch.html.

**Comment by agahkarakuzu** [comment]
@zrazi do you have any updates or questions?

**Comment by zrazi** [comment]
Thanks for reaching out. I think I am doing something wrong and I don't understand what that is. I ran the example code on Matlab ( via Citrix Receiver) and it saw the result nicelt. But still having problem with the JupyterLab. I ran the qMRLab.m first. But when I try to run the example like qMRinfo('vfa_t1'), it does nothing and keeps showing me the * sign. Not sure how to fix it. Thanks

**Comment by agahkarakuzu** [comment]
@zrazi `qMRLab.m` attempts opening GUI, which is not possible with JupyterLab interface. Can you try `startup;` instead of `qMRLab`?

**Comment by zrazi** [comment]
No, which I am is because of my not so good programming skill. I decided to switch back to the Matlab version since I am more comfortable if I can visually see the interface. Thanks for checking on me.

**Comment by agahkarakuzu** [comment]
Happy to know that GUI makes a comfortable option, yet if you need any help with CLI, just ping us ;) 

Cheers, 
Closing the issue.
