### ISSUE TITLE
mono_t2 default fitting

### ISSUE THREAD

**Issue by ileppe** [qMRLab/qMRLab#372]
Choosing the default fitting options for the model,compare to the implementation by Siemens `T2map`:
 - `Exponential`: the `Linear` fit results are noisier and some voxels don't converge
![siemens-vs-expo-vs-linear](https://user-images.githubusercontent.com/28764708/73976085-9445a100-48f5-11ea-9cde-ee991e13fea6.png)

 - `DropFirstEcho`: `false`

**Comment by agahkarakuzu** [comment]
#373
