### ISSUE TITLE
mono_t2 error and not included

### ISSUE THREAD

**Issue by little-ear** [qMRLab/qMRLab#392]
I am new to matlab (student version), new to github, and also new to qMRLab. Hopefully my report is valid and you can help me.

1) 'mono_t2' is not included in qMRLab-2.3.0. Thus, https://qmrlab.readthedocs.io/en/master/mono_t2_batch.html can not be executed as described. 

2) Manual download and adding 'mono_t2.m' to 'qMRLab-2.3.0/src/Models/T2_relaxometry' does not work either: Following Error: 

Running 'qMRLab' produces the following Error output

> Unrecognized method, property, or field 'getLink' for class 'mono_t2'.
> 
> Error in mono_t2 (line 70)
>             obj.onlineData_url = obj.getLink('https://osf.io/kujp3/download?version=1','https://osf.io/ns3wx/download?version=1');
> 
> Error in qMRLab>qMRLab_OpeningFcn (line 93)
>         Model = Modelfun();
> 
> Error in gui_mainfcn (line 220)
>     feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});
> 
> Error in qMRLab (line 37)
>     gui_mainfcn(gui_State, varargin{:});

Executing CLI
Model = mono_t2;

Error Output:

> Unrecognized method, property, or field 'getLink' for class 'mono_t2'.
> 
> Error in mono_t2 (line 70)
>             obj.onlineData_url = obj.getLink('https://osf.io/kujp3/download?version=1','https://osf.io/ns3wx/download?version=1');

What did I do wrong? Is there a solution?

Thank you in advance!

**Comment by agahkarakuzu** [comment]
Hi @little-ear, `mono_t2` was added on release [`2.4.0`](https://github.com/qMRLab/qMRLab/releases), can you give it a try with that version? On the latest doc, you can use the binder badge on [`mono_t2`](https://qmrlab.readthedocs.io/en/master/mono_t2_batch.html) to try it out on your web browser.

Our documentation points to the latest (`master`), but now I am convinced that I'll build and push versions for previous releases (from `2.3.0` on). [This](https://qmrlab.readthedocs.io/en/v2.3.0/) is the documentation for v2.3.0, as you can see,`mono_t2` is not there.

**Comment by agahkarakuzu** [comment]
And congrats on your first issue 🎊 :)

**Comment by little-ear** [comment]
Indeed, in the lower right corner are the "versions" of the documentation and I missed to check it! Thank you.
