### ISSUE TITLE
[Wiki] Create model: qMRLab_static_Models.m not found

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#396]
Hey Agah,

 Is step 11 of the wiki deprecated? https://github.com/qMRLab/qMRLab/wiki/Guideline:-Adding-a-new-Model

qMRLab_static_Models.m is not in my path.

**Comment by agahkarakuzu** [comment]
This is on `master`

https://github.com/qMRLab/qMRLab/blob/de27734b5b1a0874877c8b7135eb46c090d08a81/src/Common/qMRLab_static_Models.m

**Comment by agahkarakuzu** [comment]
This is now clear on the wiki page.
