### ISSUE TITLE
VFA_T1 fit error when using B1map

### ISSUE THREAD

**Issue by annapbarnes** [qMRLab/qMRLab#401]
## Expected Behavior
Produce sensible T1map when loading in 4D VFA nifti file + B1map nifti file.

## Actual Behavior
T1map has a lot of NaN voxel values and the voxel fit looks terrible even though the values from the T1 images follow the expected signal change.

Is there something wrong with my B1 map and how can I tell?

## Steps to Reproduce the Problem

  1. Fit data with B1 map - error occurs
  1. Fit data without B1 map - error does not occur but cannot do voxel fit.
  1. 

## Specifications

  - Version: 2.3.0
  - Platform: MSOX Catalina
  - Subsystem: Matlab R2015b + image processing toolbox

**Comment by agahkarakuzu** [comment]
@annapbarnes can you please use version 2.4.0 and see the issue persists?

 We resolved some GUI bugs causing the problems you reported.

**Comment by annapbarnes** [comment]
FYI when I click on the link from the how to install page I get a "not found" error 
https://github.com/qMRLab/qMRLab/releases/latest/download/qMRLab_latest.zip

**Comment by agahkarakuzu** [comment]
Please try:

https://github.com/qMRLab/qMRLab/archive/v2.4.0.zip

Did we point to that link for the latest release? If so, I'd be happy if you can tell me where did you click that link and I'll update it.

**Comment by annapbarnes** [comment]
oh yes sorry 

https://qmrlab.readthedocs.io/en/master/install.html

Then a little bit down it says 

Download the latest stable release **here**.
Scroll down to the page, download links are under the Assets tab.
Extract the downloaded .zip or .tar.gz file to a directory of your choice.

**Comment by annapbarnes** [comment]
oh and also from this page
https://qmrlab.org

download button goes to 2.3.0 which is what I downloaded first time.

**Comment by agahkarakuzu** [comment]
Thank you @annapbarnes I will make that link update a part of the release process.
