### ISSUE TITLE
How do I create a batch script for VFA_t1 for many subjects

### ISSUE THREAD

**Issue by annapbarnes** [qMRLab/qMRLab#402]
## Expected Behavior
model=vfa_t1; % create an instance of the model
qMRgen Batch (model)

## Actual Behavior
>> model=vfa_t1;
>> qMRgen Batch (model)
Undefined function or variable 'qMRgen'.

## Steps to Reproduce the Problem

  1. typed in at command line following instructions on https://qmrlab.readthedocs.io/en/master/batch_example.html?highlight=batch#run-the-batch
  1. I'd like to run this on 30 data sets. all with the same FAs and TR
  1.

## Specifications

  - Version: 2.3.0
  - Platform: OSX Catalina
  - Subsystem: Matlab 2015b with image processing toolbox

**Comment by agahkarakuzu** [comment]
@annapbarnes the function call should be:

```
model = vfa_t1;
qMRgenBatch(model);
```

I see that in the documentation there is an extra space between `qMRgen` and `Batch`, I will fix this asap. 

You can see a working example (online) here:

https://mybinder.org/v2/gh/qMRLab/doc_notebooks/master?filepath=vfa_t1_notebook.ipynb

**Comment by agahkarakuzu** [comment]
Interesting, the documentation is correct when I visit the documentation:
![image](https://user-images.githubusercontent.com/9632322/89403986-3a2c6980-d6e7-11ea-8ace-d026415d4678.png)

But when  I click the link you sent that highlights `batch`,  there is a mysterious space between the `qMRgen` and `Batch`, which is normally not there :

![image](https://user-images.githubusercontent.com/9632322/89404108-7233ac80-d6e7-11ea-99af-1d16bde458de.png)

**Comment by annapbarnes** [comment]
fixed 👍
