### ISSUE TITLE
problems with GUI on Matlab R2015b OSX Catalina

### ISSUE THREAD

**Issue by annapbarnes** [qMRLab/qMRLab#403]
problems with GUI on Matlab R2015b OSX Catalina

## Expected Behavior
use arrow buttons to move through volumes in 4D image
use mouse to window, zoom or pan 

## Current Behavior
arrow buttons do not scroll through 4D image
cannot get out of whichever mode the mouse was clicked into eg can't stop the windowing, pan or zoom unless I restart the application.

## Possible Solution

probably a matlab X OSX interaction 

## Steps to Reproduce

1. Every time I open the application on my MacBook
1.
1.
1.

**Comment by agahkarakuzu** [comment]
With qMRLab version `v2.4.0`, R2015b on OSX Mojave, I am not running into this problem. Can you try with the newer qMRLab version?

**Comment by annapbarnes** [comment]
fixed 👍
