### ISSUE TITLE
How do I run vfa_t1 on all the data sets in my directory

### ISSUE THREAD

**Issue by annapbarnes** [qMRLab/qMRLab#404]
## Expected Behavior
vfa1_t1_batch from CL

## Actual Behavior
via_t1_batch from CL only runs on first 4D data set

## Steps to Reproduce the Problem

  1. put 1 4D image in directory runs OK
  1. put another 4D image in directory with added ID - error message saying wrong filename (obviously)
  1. Do I have to write my own loop inside the Matlab script or do you have one setup already

## Specifications

  - Version: 2.4.0
  - Platform: MacOSX catalina
  - Subsystem: Matlab 2015b

**Comment by agahkarakuzu** [comment]
@annapbarnes the script generated by `qMRGenBatch` is for one dataset only. You will need to wrap that in a simple loop to deal with other images, which are favorably nicely organized in multiple folders.

**Comment by annapbarnes** [comment]
Thank you - I guessed as much - just wanted to make sure I wasn't re-inventing the wheel.
