### ISSUE TITLE
OSX quarantined mex files

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#408]
I received an email from a user that she could not start qMRLab. I figured that it was because OSX (Catalina 10.15.7) quarantined mex files.  

```
sudo xattr -r -d com.apple.quarantine $qMRLab_directory

sudo find $qMRLab_directory -name \*.mexmaci64 -exec spctl --add {} \;
```

This solved the problem, I will add this to the documentation under a new section (`Known Issues`) under Installation.

**Comment by mathieuboudreau** [comment]
>I figured that it was because OSX (Catalina 10.15.7) quarantined mex files.

Wait, what? The latest OSX version quarintined all the mex files on systems?

**Comment by agahkarakuzu** [comment]
They could not help but quarantine something in 2020. Interestingly, I had the exact same MATLAB and OS versions with the user, but I did not run into this issue. All I know is that Catalina is not being a research friendly release so far, and Big Sur does not make things better.

**Comment by spinicist** [comment]
It may depend on how the user downloads qMRLab. As I understand it, Safari does the quarantining rather than something at OS level. Certainly, if people download QUIT via Safari it gets quarantined, but if they use `curl` it doesn't. I've just realised I haven't tried downloading QUIT via Chrome, I should try that and see what happens.

**Comment by agahkarakuzu** [comment]
@spinicist thanks! That makes sense, I always use git, probably why I bypassed this issue (similar to curl does, I guess). It is worth experimenting safari/chrome downloads and add them into documentation. At any rate, making quarantine decision based on through which channel they are downloaded rather than what is downloaded almost sounds like a fallacy.
