### ISSUE TITLE
Migrating tests from TravisCI 

### ISSUE THREAD

**Issue by notZaki** [qMRLab/qMRLab#412]
The current tests are using travis-ci **.org** which will be closed down by the end of the year [[ref]](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-when-will-the-migration-from-travis-ciorg-to-travis-cicom-be-completed).

The tests can be migrated to travis-ci **.com** however, from what I understand, it is no longer free. They now offer a free trial with 1000 minutes, after which we'd either have to switch to a paid plan or ask for 'OSS minutes' [[ref]](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

Just wondering if there's any plans on what to do for the tests. Are the self-hosted agents (#325) or Github Actions [[ref]](https://github.com/joergbrech/moxunit-action) viable alternatives?

**Comment by mathieuboudreau** [comment]
Huh - thanks for letting us know!

Looks like we might need to switch to a self-hosted service then =( @agahkarakuzu thoughts? Also @jcohenadad were you aware?

**Comment by spinicist** [comment]
My two pence - Github actions are great! I have no idea how well they play with Matlab, but having used Travis, Azure Pipelines and Github Actions I found actions the easiest by far.

**Comment by jcohenadad** [comment]
> Also @jcohenadad were you aware?

yes [we are](https://github.com/neuropoly/spinalcordtoolbox/pull/2739#issuecomment-640671269), and currently debating where should we go. Our other projects are on Github actions and we love it but SCT has a lot of Travis-specific  CI code (notably to set up all the platform via custom docker images).

**Comment by agahkarakuzu** [comment]
Octave [MoxUnit GH Action](https://github.com/marketplace/actions/moxunit-action) is using qMRLab's env:

https://github.com/joergbrech/moxunit-action/blob/f02a706db8a4db8e311041bd8d6853a559001d29/Dockerfile#L2

So GH is pretty straightforward, but this is a good opportunity to branch another one for MATLAB on Azure's new add-on. We also need to consider timeout limits.

**Comment by agahkarakuzu** [comment]
@notZaki Azure self-hosted agents is a really cool & viable option as long as you can maintain a machine for that. Microsoft hosted agents offer all the matlab features (but transformation and compiler products) for public projects. You can see an example [here](https://dev.azure.com/neuropoly/qMRLab/_build/results?buildId=1008&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9). There are some hiccups, but functionality there and integration is quite straightforward. My final plan is:
- GitHub actions for Octave CI
- Azure Matlab Extension on self-hosted 10 agents for MATLAB CI 
- Azure self-hosted for release pipelines to deal with documentation update and building standalone app & docker images.

**Comment by agahkarakuzu** [comment]
This is done, Mathworks did a pretty good job with the Azure extension! I added the badge in README, you can see the builds.
