### ISSUE TITLE
How to get qMT mask by original DATA?

### ISSUE THREAD

**Issue by twu3565** [qMRLab/qMRLab#415]
## Expected Behavior
Teach me the process to create mask by original DATA, what kind software or batch can achieve the MASK?

## Actual Behavior
I am studying the qMT and we are trying to create the MASK to accelerate the qMT reading.
But I am stuck in use original DATA to create the MASK.
So far I am use ImageJ open the DICOM image draw a loop then clear outside.
But ImageJ cannot output DATA as DICOM.
So can some one know how to create the mask teach me?

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: master
  - Platform: qmt_spgr
  - Subsystem: matlab

**Comment by agahkarakuzu** [comment]
Hi @twu3565, assuming that you are processing brain data, you may want to consider brain extraction tools. You can use one of your qMT images as input for example, to [FSL's BET](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BET/UserGuide). This would give you a brain mask in the same domain (in nifti format), that you can use as an input. There is a threshold ([0-1] ~0.45 by default afaik) that you can play with to adjust how inclusive/exclusive your mask will be.

For now, we are using BET in our [pipelines](https://qmrlab.readthedocs.io/en/master/qmrflow_mtsat.html) and it usually does a good job for mt weighted data. Although we don't have one for `qMT` yet.

If you are not working with brain data and there is not an automatic segmentation tool made available for your anatomy of interest, then you may check [3D Slicer](https://www.slicer.org/) for manual segmentation. Using [segment editor](https://slicer.readthedocs.io/en/latest/user_guide/modules/segmenteditor.html), you can first save your labelmap in `nhdr` (that's what Slicer allows in the first step), then load them again, then export as `nii`. If you are not interested in a specific target, but just would like to perform a simple thresholding to remove background, you can find useful tools for that in the segment editor too.

**Comment by twu3565** [comment]
Thank you for your fast response.
Yes, we are trying to reconstruct Brain qMT now but we did focus on Calf muscle so your advice is pretty useful.
I will try to use FSL's BET ASAP and post the result.
You give me a pretty good direction.
Thanks again
And Happy New Year

TI WU

**Comment by agahkarakuzu** [comment]
@twu3565 I saw several papers using CNN to segment leg muscles (they were usually thigh, but there would be some for calf ). However, not sure if they publicly shared trained models and whether the contrast/resolution characteristics would be a good fit for the msk data you are going to acquire. 

A few years ago I was using a custom morphometry-based script to do background segmentation for calf muscles acquired using3 D TurboFLASH, maybe we can tweak that for your purposes. But as I noted previously, you can get pretty good results by some simple thresholding on 3D slicer. When it comes to segmenting individual muscle groups, manual segmentation requires some expertise with the anatomy and for automatic methods, a literature/open-code search would be needed.

**Comment by twu3565** [comment]
Thanks, I'll check it out!

**Comment by twu3565** [comment]
Good Evening

I read the message you send to me and have other questions.

I believe you know my Chair Professor Usha, and we are trying to study qMT
based on the paper "Quantitative Magnetization Transfer in In Vivo Healthy
Human Skeletal Muscle at 3T" published in 2010.

Do you have some suggestions for further references?

We are facing the fraction we made are around 2-3% but paper can show
around 8%.

I installed the fsl and tried to run the Bet but input has something wrong
with it so I cannot create the mask file.

Does fsl have a requirement for a nii file?

Thank you

TI WU

**Comment by agahkarakuzu** [comment]
@twu3565 I am aware of the underestimation issue you are having. To help solve this, McGill site will share a pulse sequence. The example brain data you are working on is acquired there. 

Afaik Sinclair's work is the most comprehensive exploration of qMT in skeletal muscle. 

FSL can easily work with nifti files. In your case the `qmt.nii` has 11 scalars, which may confuse BET.  I resampled/cropped a T1w image for the corresponding MT field of view. I can send them to you if you can reach me by email (agahkarakuzu@gmail.com), I can send them to you.
