### ISSUE TITLE
Error in fitting mono_t2, returning undefined values at initial point (lsqnonlin).

### ISSUE THREAD

**Issue by little-ear** [qMRLab/qMRLab#417]
I am using the mono_t2 model (cli) to fit almost the whole FOV. In addition, I have a lot of samples to test with small variations. 
Thus, I was hoping to be able to fit the whole data set at once without the need to define a mask (time constrains). 

When starting the fitting process, I get the following error: 

> =============== qMRLab::Fit ======================
> Operation has been started: mono_t2
> Error in voxel [1,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue.
> Unrecognized function or variable 'tempFit'.
> 
> Error in FitData (line 156)
>         if isempty(tempFit), Fit=[]; return; end
> 
> Error in merge_and_fit_T2 (line 34)
> FitResults = FitData(data,Model);

When fitting the T1 IR model, it works flawlessly (also without mask). 

May I ask another question; In the documentation I could not find the CLI code in order to skip the first echo? 

Thank you in advance. 

Here is the script I run.

```
clear;
fileFolder = fullfile('./data');
files=dir(fullfile(fileFolder, '*.nii'));
fileNames={files.name};
for k = 1:numel(fileNames)
    fname = fullfile(fileFolder, fileNames{k});
    z(k) = load_untouch_nii(fname); 
    y(:,:,:,k) = z(k).img;
end
output=make_nii(y);
save_nii(output, 'SEData.nii');
Model = mono_t2; 
Model.Prot.SEdata.Mat=[50:50:1600]';
data = struct(); 
data.SEdata= double(y);
FitResults = FitData(data,Model);
FitResultsSave_nii(FitResults);
clear;
```

**Comment by agahkarakuzu** [comment]
@little-ear I noticed that when the solver cannot find the solution for the very first voxel (`[1, 1, 1]`), this creates an exception, which is a bug we'll address. For any other voxel w/o solution, the fit will carry on by indexing them. In the short term, you would not run into this issue using a mask. 

`inversion_recovery` is not subjected to the same exception, as it is not using `lsqnonlin` for NLS, but using the implementation described [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2962940/).

For dropping first echo on CLI:

```
Model = mono_t2;
Model.options.DropFirstEcho = true;
```

should do that.

**Comment by agahkarakuzu** [comment]
@little-ear I pushed a bugfix for your issue, available at the `fit_exception` branch. I'll wait on integration tests before merging it to the master. Thank you for reporting this problem!

**Comment by little-ear** [comment]
@agahkarakuzu 
Thank you for the fast bugfix. I tried it and it seems to run smoothly now. 
However, I also noticed something else: Only 1 of my 8 cores were working on the fitting (100%; rest unter 10%). 

I saw the following posts on mathworks : 
https://www.mathworks.com/matlabcentral/answers/68005-is-it-possible-to-perform-parallel-computing-with-lsqnonlin
https://www.mathworks.com/help/optim/ug/lsqnonlin.html

It seems that it is possible, but I do not dare to play with qMRLab code [UseParallel].

**Comment by agahkarakuzu** [comment]
@little-ear parallelization of the voxelwise fit tasks is not easily possible because of the way indexes are sorted currently. Besides, changing to parallel loops requires choosing the right strategy (there are several in Matlab) to minimize overhead. I have an idea to implement this at a higher level, where fit calls can be evoked in a shamelessly parallel way. You'll be first to know when I complete it, user requests kindle motivation :)

**Comment by agahkarakuzu** [comment]
@little-ear now on the [`distribute`](https://github.com/qMRLab/qMRLab/tree/distribute) branch, you can give parallel processing a try! It goes parallel if parallel workers exist. So, you can just 

```
parpool
```

on the command window, then fit. 

Let me know how it goes!

**Comment by agahkarakuzu** [comment]
BTW, I did not try this from the CLI, but using FitDataPar instead of FitData may work.

**Comment by agahkarakuzu** [comment]
- [ ] Add documentation about cli access to prots and options. 
- [ ] Test and add documentation about parfit (this is a better name) on CLI.
- [ ] MapData can split inputs across cores based on histogram, the more evenly fg/bg voxels are distributed across workers, the more efficient parallelization becomes.

**Comment by little-ear** [comment]
@agahkarakuzu 
I started `parool` in the command window. 
Then i ran my code (see above) with the following changes: 
`FitResults = FitDataPar(data,Model);`

However, I get the following error: 
=============== qMRLab::Fit ======================
<< i >> Operation has been started:  mono_t2 
<< :: >> Parallel:  8 workers 
<< - >> Modal windows have been disabled 
<< ! >> Temporary result saving has not been implemented in parallel mode yet. 
  0%[>                                                  ]
Solution not found for the voxel [1,145,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Solution not found for the voxel [1,289,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Error using FitDataPar (line 163)
Reference to non-existent field 'fields'.

So, I assume the same problem as before: lsqnonlin can not find result and breaks the iterations.

Error in merge_and_fit_T2 (line 34)
FitResults = FitDataPar(data,Model);

**Comment by agahkarakuzu** [comment]
Probably one of the cores hit bg voxels only, I'll fix it. Thank you! Do you get the same error using GUI? You can save your reduced input matrix as a mat file (containing only the input image), then load into **SEData** from GUI.

**Comment by agahkarakuzu** [comment]
OK based on what I thought the issue would be, I pushed a commit c9bb25086d6d9e9bbde52694296a1cace6ab42dc. If it does not solve your issue, seeing the entire trail of the error you get would be helpful.

**Comment by little-ear** [comment]
Sorry for my late reply; I had to do some MR measurements ;) 

Results from GUI processing only (step by step): 

Here is my phantom (screenshot)
![wholephantom](https://user-images.githubusercontent.com/59336624/104738232-8aebc800-5745-11eb-88be-3b09165dd864.png)

1) I activated Parallel Pool (open matlab; in the standard view, in the lower right corner 'Start Parallel Pool'; However, I adjusted in the settings 'Parallel preferences' the number of workers to fit the actual number of cores). All cores are running fine. Side info: Now the progress bar is not working anymore (as seen on single cores).

2) I drew a mask which had very 'little' background noise (from small-walled acrylic glas containers).
![Maskinnerphantom](https://user-images.githubusercontent.com/59336624/104738711-2aa95600-5746-11eb-9d92-bd932c3b5d6a.png)
All worked fine and super fast!!!
> =============== qMRLab::Fit ======================
> << i >> Operation has been started:  mono_t2 
> << :: >> Parallel:  8 workers 
> << - >> Modal windows have been disabled 
> << ! >> Temporary result saving has not been implemented in parallel mode yet. 
>   0%[>                                                  ]
> Solution not found for the voxel [258,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [141,186,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [141,187,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [141,188,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [257,218,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [324,164,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [141,189,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [142,191,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [309,166,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [142,192,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [303,192,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [289,220,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [334,192,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [304,193,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [143,194,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [289,221,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [98,222,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [328,166,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [308,167,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [152,168,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [288,222,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [287,223,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [153,168,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [307,168,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [331,168,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [332,169,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [286,224,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [100,225,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [263,225,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [285,225,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> 
>  38%[===================>                               ]
> Solution not found for the voxel [188,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [189,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [190,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [191,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [192,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [193,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [194,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [196,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [198,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [199,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Errorenous fit warnings will be silenced for this process.
> Plea
>  50%[=========================>                         ]
> Solution not found for the voxel [276,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [277,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [278,1,1]: Objective function is returning unde
>  75%[======================================>            ]
> Solution not found for the voxel [149,170,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Errorenous fit warnings will be silenced for this process.
> Plea
>  62%[===============================>                   ]
> Errorenous fit warnings will be silenced for this process.
> Plea
> 100%[==================================================>]
> Plea
> 100%[===================================================]
> Elapsed time is 20.417298 seconds.
> << * >> Operation has been completed:  mono_t2 
> << i >> FitResults will be saved to your working directory: 
>       - If specified in the GUI, to the Path Data. 
>       - Otherwise at /home/marcos/ram_disk/T2_50_TR10_HR 
> ==================================================


3) Now I tried a Mask which had 'normal' background noise (with 'outer shell'/'normal sized' acrylic glas containers). However, no results/folder was created. 
![maskwholephantom](https://user-images.githubusercontent.com/59336624/104738856-56c4d700-5746-11eb-96dd-3db50ff598c0.png)
> =============== qMRLab::Fit ======================
> << i >> Operation has been started:  mono_t2 
> << :: >> Parallel:  8 workers 
> << - >> Modal windows have been disabled 
> << ! >> Temporary result saving has not been implemented in parallel mode yet. 
>   0%[>                                                  ]
> Solution not found for the voxel [234,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,85,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,121,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,157,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [304,193,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,230,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,122,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,123,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,158,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,159,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,194,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [143,194,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [175,194,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [333,194,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,195,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [107,230,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,231,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,51,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,86,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,87,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,124,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [144,195,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [175,195,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [332,195,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,196,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,52,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,53,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,88,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,160,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,161,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [111,231,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [113,231,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [114,231,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [117,231,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,232,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,125,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,126,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,162,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [2,232,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,233,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Errorenous fit warnings will be silenced for this process.
> Solution not found for the voxel [1,54,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,55,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,89,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,90,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,127,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,128,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,163,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,56,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,57,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,91,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,129,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,130,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,164,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,58,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,92,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,93,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Errorenous fit warnings will be silenced for this process.
> Solution not found for the voxel [1,59,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,60,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [324,164,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [1,165,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Errorenous fit warnings will be silenced for this process.
> Errorenous fit warnings will be silenced for this process.
> Solution not found for the voxel [1,94,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Errorenous fit warnings will be silenced for this process.
> Solution not found for the voxel [239,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [240,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [241,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [244,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [247,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [248,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [257,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [258,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [259,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Errorenous fit warnings will be silenced for this process.
> Plea
>  12%[======>                                            ]
> Solution not found for the voxel [188,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [189,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [190,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [191,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [192,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [193,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [194,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [196,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [198,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Solution not found for the voxel [199,324,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
> Errorenous fit warnings will be silenced for this process.
> Plea
>  25%[=============>                                     ]
> Plea
>  38%[===================>                               ]
> Plea
>  50%[=========================>                         ]
> Errorenous fit warnings will be silenced for this process.
> Plea
>  62%[===============================>                   ]
> Plea
>  75%[======================================>            ]
> Plea
> 100%[==================================================>]
> Plea
> 100%[===================================================]
> Elapsed time is 33.717073 seconds.
> << * >> Operation has been completed:  mono_t2 
> << i >> FitResults will be saved to your working directory: 
>       - If specified in the GUI, to the Path Data. 
>       - Otherwise at /home/marcos/ram_disk/T2_50_TR10_HR 
> ==================================================
> Index in position 1 is invalid. Array indices must be positive integers or logical values.
> 
> Error in FitDataPar (line 365)
>          Fit.(cur_field)(x_i,y_j) = cur_fit.(cur_field)(kk,4);
> 
> Error in qMRLab>FitGo_FitData (line 415)
>        FitResults = FitDataPar(data,Model,1);
> 
> Error in qMRLab>FitGO_Callback (line 388)
> FitGo_FitData(hObject, eventdata, handles);
> 
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> 
> Error in qMRLab (line 41)
>     gui_mainfcn(gui_State, varargin{:});
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)qMRLab('FitGO_Callback',hObject,eventdata,guidata(hObject)) 
> Error while evaluating UIControl Callback.

4) same issue without a mask.

Attached is the used data: 
[data.zip](https://github.com/qMRLab/qMRLab/files/5821104/data.zip)

I hope this is helpful.

**Comment by agahkarakuzu** [comment]
This is a pretty cool phantom @little-ear! Progress bar in a model window is disabled on purpose to keep worker jobs isolated.

I will look into the issue you had, fitting completes successfully but looks like there is a bug while parsing data from workers back into the original domain. The data you uploaded will be of great help! 

Cheers

**Comment by agahkarakuzu** [comment]
@little-ear I fixed the bugs causing those issues, thank you so much for sharing your data! I am working on finalizing temporary result saving functionality, I'll merge this branch when it is ready.

**Comment by agahkarakuzu** [comment]
Before I forget, T2 values are now in seconds to follow a data standard.

**Comment by agahkarakuzu** [comment]
Leaving this here as a funny demonstration of transitivity of floating point precision. Stripe-patterns are introduced by multicore processing the remaining portion of (~30%) autosaved data, which was again, saved in a multi-core process: 

![image](https://user-images.githubusercontent.com/9632322/104846694-cdc6b080-58a9-11eb-84a7-8b11deafc7a3.png)

**Comment by agahkarakuzu** [comment]
Okay, this branch is about to be finished. I think I solved all the issues above (including that stripes). Now ParFitData save has `autosave` (every 5 min) functionality!
