### ISSUE TITLE
Apple M1 chip compatibility

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#429]
Since I just got a new MBP with the Apple M1 chip, I thought I'd open an issue discussing my experience and for anyone else to also chime in if they encounter issues.

Computer: MacBook Pro (13-inch, M1, 2020)
CPU: Apple M1
MATLAB version:  MATLAB R2018b

Overall, qMRLab seems to work as intended with MATLAB run with the Rosetta 2 interpreter (automatically, I didn't need to specify it). Note that my MATLAB version isn't officially supporting M1 (MATLAB only promises that for  MATLAB R2020b Update 3), however MATLAB & qMRLab still worked!

I ran most of the unit tests, opened the GUI, and ran the inversion recovery demo, and didn't encounter any errors anywhere in my experience.

<img width="1440" alt="Capture d’écran 2021-02-10 à 11 54 34" src="https://user-images.githubusercontent.com/1421029/107531493-78737b80-6b97-11eb-821f-69529949689a.png">

**Comment by agahkarakuzu** [comment]
Great news @mathieuboudreau ! Happy that you were able to get the license manager work for you :)

**Comment by agahkarakuzu** [comment]
https://qmrlab.readthedocs.io/en/master/known-issues.html#apple-silicon-m1-compatibility
