### ISSUE TITLE
Unrecognised Function or Variable ‘vfa_t1’

### ISSUE THREAD

**Issue by AlexMorello** [qMRLab/qMRLab#449]
Hello, devs,

I’m trying to compute T1 maps for a set of NIfTIs as per https://qmrlab.readthedocs.io/en/master/vfa_t1_batch.html. However, the error persists, that is regardless of the code itself. Any suggestions are very much appreciated!

**Comment by mathieuboudreau** [comment]
Hi @AlexMorello,

Could you confirm the MATLAB version that you're using, and that you followed the [installation instructions](https://qmrlab.readthedocs.io/en/master/install.html) (all the way to running the `startup` command inside the folder, which add the subfolders to the MATLAB path).

If so, are you able to run either `qMRLab` and/or `qMRLabVer`?

**Comment by AlexMorello** [comment]
> Hi @AlexMorello,
> 
> Could you confirm the MATLAB version that you're using, and that you followed the [installation instructions](https://qmrlab.readthedocs.io/en/master/install.html) (all the way to running the `startup` command inside the folder, which add the subfolders to the MATLAB path).
> 
> If so, are you able to run either `qMRLab` and/or `qMRLabVer`?

Bonjour, Matthieu, 

I now am. Figured out how to launch the GUI, too. Trying to feed the data into it yields the following: ‘Protocol has: 2 rows. And input volume VFAData has 1 frames.’

**Comment by mathieuboudreau** [comment]
Great!

To know more about the expected data format, I recommend you download the demo data through the GUI, and copy the format of the data we've provided. This sounds like your different flip angles are not included in the dataset you're trying to load (in the 4th/time dimension); i.e., you might be trying to load a single flip angle instead of both flip angles. If you need further help to figure out how to properly format your data after trying it out a bit more, let us know the format of the dataset you have (e.g. NIfTI/matlab file/etc).

**Comment by AlexMorello** [comment]
Hello, Matthieu,

Thank you very much for responding so promptly! I’ve got a bunch of T1 VIBE’s (NIfTI) acquired at different flip angles. Now, I need to create a fit for the dataset using the VFA technique.

**Comment by mathieuboudreau** [comment]
Hi Alex,

Do you have FSL installed? If so, I think you can use `fslmerge -t outfile infile1 infile2` to concatenate NIfTI images in the time (fourth) dimension, and then load that output file into qMRLab.

You can download our demo data (https://osf.io/7wcvh/) and compare the format of `VFAData.nii.gz` (e.g. using `fslinfo file` on both.

**Comment by AlexMorello** [comment]
> Hi Alex,
> 
> Do you have FSL installed? If so, I think you can use `fslmerge -t outfile infile1 infile2` to concatenate NIfTI images in the time (fourth) dimension, and then load that output file into qMRLab.
> 
> You can download our demo data (https://osf.io/7wcvh/) and compare the format of `VFAData.nii.gz` (e.g. using `fslinfo file` on both.

Done! May you please take a look at the output? It comprises two series acquired at 2 and 3 degrees respectively. The TR was set to 2.1 ms.

https://drive.google.com/drive/folders/13x50n6p_BH23kB2g2qji3t4Z7IYs8UPk?usp=sharing

**Comment by mathieuboudreau** [comment]
Hi @AlexMorello,

Thanks for sharing your results.

The maps don't look that good to me.

<img width="888" alt="Screen Shot 2021-09-25 at 2 48 54 PM" src="https://user-images.githubusercontent.com/1421029/134781203-81102f64-b183-4676-be0c-cbc66ce34e75.png">

I don't know what your sample is, but a lot of spacial variations.

The first two things that pop out to me are 1) did you use a B1 map, and did that look correct? and 2) I noticed you used flip angles of 2 and 3 degrees, and these are very close together. Typically a wider range is used (e.g. 3 and 20 degrees), so this might have played a role.

<img width="531" alt="Screen Shot 2021-09-25 at 2 50 46 PM" src="https://user-images.githubusercontent.com/1421029/134781244-0bb12e81-b394-4285-8118-9f1c8ae3ed9a.png">

**Comment by agahkarakuzu** [comment]
### Option-1 using `FitResults.mat`

![image](https://user-images.githubusercontent.com/9632322/137210983-7a08e893-e83f-40ac-bac7-8ee6f86f3c97.png)

With `vfa_t1` selected, click `Load Results` and point to `FitResults.mat` 

### Option-2 Drag-drop a nii image on MATLAB's command window

Our 3D viewer will recognize the file and open it. It has all the ROI tools:

![image](https://user-images.githubusercontent.com/9632322/137211266-a516a475-0447-4abf-8ee8-195db10cab30.png)

The respective command is:

```
uiopen('your_nii_image',1);
```

More info for ROI toolbox is available [in the docs](https://qmrlab.readthedocs.io/en/master/gui_usage.html).

**Comment by AlexMorello** [comment]
> ### Option-1 using `FitResults.mat`
> 
> ![image](https://user-images.githubusercontent.com/9632322/137210983-7a08e893-e83f-40ac-bac7-8ee6f86f3c97.png)
> 
> With `vfa_t1` selected, click `Load Results` and point to `FitResults.mat`. This will also show your protocol settings etc.
> 
> ![image](https://user-images.githubusercontent.com/9632322/137211725-78aed276-50b2-4bbb-9fce-dccb060fa5c8.png)
> ### Option-2 Drag-drop a nii image on MATLAB's command window
> 
> Our 3D viewer will recognize the file and open it. It has all the ROI tools:
> 
> ![image](https://user-images.githubusercontent.com/9632322/137211266-a516a475-0447-4abf-8ee8-195db10cab30.png)
> 
> The respective command is:
> 
> ```
> uiopen('your_nii_image',1);
> ```
> 
> More info for ROI toolbox is available [in the docs](https://qmrlab.readthedocs.io/en/master/gui_usage.html). Under the source dropdown, you can switch between `M0` and `T1`.

I see! You folks are geniuses; thank you very much indeed!

**Comment by agahkarakuzu** [comment]
This issue has been resolved.
