### ISSUE TITLE
Struct field conflict on exporting uncorrected maps

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#451]
![image](https://user-images.githubusercontent.com/9632322/137064458-cc945c8a-fea2-408f-aa58-951edfd1a587.png)

@jvelazquez-reyes we also have [simulation tests](https://dev.azure.com/neuropoly/qMRLab/_build/results?buildId=1424&view=logs&j=1854c763-fba6-56d2-6006-ca56e339d521&t=4781830f-296f-5976-880f-a6b921719dfe) running. It expects outputs to be the same (with what is saved) after modification. 

When the default for exporting uncorrected maps is `false`, expected fields (e.g. `T1` and `M0`) cannot be found in simulations. Please change default to true and see if this issue is resolved. If not, we'll need to find a solution to that.

**Comment by agahkarakuzu** [comment]
Thanks for the latest changes @jvelazquez-reyes ! Looks like we have a test assertion failure for the `mp2rage`: 

https://dev.azure.com/neuropoly/qMRLab/_build/results?buildId=1429&view=logs&j=c0e85002-b1bf-5d85-fa22-e1a871bbe3f3&t=428b0824-fd2f-5ea3-6a04-e0b334ebc4e5&l=2533

It complains that there is some change (exceeding 5%) for R1 after the latest changes pushed to the codebase. Can you look into it and see how this happened?

**Comment by jvelazquez-reyes** [comment]
I will take a look.

**Comment by agahkarakuzu** [comment]
Here's some tips for you @jvelazquez-reyes 

If you do the following (in a directory that is not qMRLab): 

```
setenv('ISCITEST','1');
qMRgenBatch(mp2rage,pwd);
setenv('ISCITEST','');
```

it will give you the script and data used in CI test. If you run `mp2rage_batch`, you will get the same error we saw on Azure. 

### Reason: 

In the example dataset we have B1map, so in the previous versions The fields `R1` and `T1` were corrected maps. Now in the presence of a `B1map` we named these as `R1cor` and `T1cor`. So right now the  mapping is: 

|Saved results | New results |
| -------------| -------------| 
|R1|R1cor|
|T1|T1cor|
|N/A| R1| 
|N/A| T1|

As you may have realized, we could have run into the same problem with `mt_sat` if there was a B1map in the example dataset. 

### Solution:

We need to update the example datasets on OSF. I can show you how to do that in a zoom call, and explain how example dataset versions are associated with qmrlab versions.

**Comment by jvelazquez-reyes** [comment]
@agahkarakuzu thanks for this detailed review. I was suspecting it had to do with those mappings you mentioned.

I think everything is covered from the task list. It would only remain to check the CIs tests after updating the example datasets.

Ah, and please show me how to update those example datasets on OSF.

**Comment by agahkarakuzu** [comment]
These issues have been resolved, thanks @jvelazquez-reyes !
