### ISSUE TITLE
Fitting Data 0% No CPU Load

### ISSUE THREAD

**Issue by AlexMorello** [qMRLab/qMRLab#462]
Dear Agah and Matthieu, 

I'm trying to fit some T2 images acquired at different _TE_s. To that end, I've t-merged a test batch of 5 _TE_s using _fslmerge_, set up a protocol in _qMRLab_, and entered the _TE_ values into it. Yet when I begin the procedure, the progress bar never moves beyond 0%. No CPU load is registered by Linux, either. It's as if the computer were actually idle instead. Here's [the batch](https://drive.google.com/drive/folders/1OaB13h09ilGseKJ_t8q8IEK9J16Jnm4_?usp=sharing) / the [merged file](https://drive.google.com/file/d/1251FolTxIruRbr1zNySIDVaypIuelV4J/view?usp=sharing).

**Comment by mathieuboudreau** [comment]
Have you successfully tested the method using the demo data we provide?

**Comment by AlexMorello** [comment]
Sorry, pushed the wrong button and closed the issue by mistake. I can't seem to download the demo batch, though. The folder remains empty and 0 bytes in size. It may be caching the data elsewhere first, so I'll let it spin for a while.

**Comment by AlexMorello** [comment]
> Have you successfully tested the method using the demo data we provide?

The output reads as follows:

'Error using downloadData (line 53)
Data cannot be downloaded: Could not establish a secure connection to "osf.io". The reason is
"error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed". Check your
certificate file (/home/alex/MATLAB/sys/certificates/ca/rootcerts.pem) for expired, missing or
invalid certificates.'

**Comment by AlexMorello** [comment]
Guys, I've attempted it on another computer to absolutely no avail :( @mathieuboudreau @agahkarakuzu

**Comment by mathieuboudreau** [comment]
> > Have you successfully tested the method using the demo data we provide?
> 
> I can't seem to download the demo batch, either. The output reads as follows:
> 
> '_Error using downloadData (line 53) Data cannot be downloaded: Could not establish a secure connection to "osf.io". The reason is "error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed". Check your certificate file (/home/alex/MATLAB/sys/certificates/ca/rootcerts.pem) for expired, missing or invalid certificates_.'

It seems your internet or computer is having difficulty downloading the dataset via MATLAB. You can download it directly via a web browser here: https://osf.io/kujp3/

There, you'll find a demo dataset and expected fit results. qMRLab should be able to fit this dataset. When you fit your own dataset, you should try to format your data as close as possible to this demo dataset (i.e. order the volume dimensions the same way, I think different TEs should be in the time/4th direction but am not 100% sure).

**Comment by AlexMorello** [comment]
> > > Have you successfully tested the method using the demo data we provide?
> > 
> > 
> > I can't seem to download the demo batch, either. The output reads as follows:
> > '_Error using downloadData (line 53) Data cannot be downloaded: Could not establish a secure connection to "osf.io". The reason is "error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed". Check your certificate file (/home/alex/MATLAB/sys/certificates/ca/rootcerts.pem) for expired, missing or invalid certificates_.'
> 
> It seems your internet or computer is having difficulty downloading the dataset via MATLAB. You can download it directly via a web browser here: https://osf.io/kujp3/
> 
> There, you'll find a demo dataset and expected fit results. qMRLab should be able to fit this dataset. When you fit your own dataset, you should try to format your data as close as possible to this demo dataset (i.e. order the volume dimensions the same way, I think different TEs should be in the time/4th direction but am not 100% sure).

Thanks - figured that out, got the demo batch, and closed the issue. It works as expected, yet I cannot quite do the same with my own dataset. Moreover, I cannot compute the B1+ map for my T1 batch, either. I'm using these two files (FA = [35](https://drive.google.com/file/d/1KF736-i6ErV2NqaRhgSifb8qfCOLQ3LX/view?usp=sharing) and [70](https://drive.google.com/file/d/1-3SIPH-bTF1y6dbBsqsHvQkT4yvRel9g/view?usp=sharing) degrees, respectively). What I get is precisely this:

```
=============== qMRLab::Fit ======================
Operation has been started: b1_dam
Array dimensions must match for binary array op.

Error in b1_dam/fit (line 83)
            FitResult.B1map_raw =
            abs(acos(data.SF2alpha./(2*data.SFalpha))./(deg2rad(obj.Prot.Alpha.Mat)));

Error in FitData (line 260)
    Fit = Model.fit(data);

Error in qMRLab>FitGo_FitData (line 406)
FitResults = FitData(data,Model,1);

Error in qMRLab>FitGO_Callback (line 388)
FitGo_FitData(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in qMRLab (line 41)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)qMRLab('FitGO_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
```
