### ISSUE TITLE
Question about T2 Fitting 

### ISSUE THREAD

**Issue by AlexMorello** [qMRLab/qMRLab#464]
I do apologise in advance for being so stubborn, @agahkarakuzu and @mathieuboudreau , but I seriously need to get this to work. Attempting to process a freshly merged (time-dimension-concatenated in _fsl_) batch of [five T2-weighted images](https://drive.google.com/file/d/1251FolTxIruRbr1zNySIDVaypIuelV4J/view?usp=sharing) of a spherical phantom acquired at different TE (4.92, 7.38, 9.84, 12.3, and 14.7, respectively) results in this:  

```
Error in voxel [1,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue.
Undefined function or variable 'tempFit'.

Error in FitData (line 156)
        if isempty(tempFit), Fit=[]; return; end

Error in qMRLab>FitGo_FitData (line 406)
FitResults = FitData(data,Model,1);

Error in qMRLab>FitGO_Callback (line 388)
FitGo_FitData(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in qMRLab (line 41)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)qMRLab('FitGO_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

Error in voxel [1,1,1]: Array indices must be positive integers or logical values.
Undefined function or variable 'tempFit'.

Error in FitData (line 156)
        if isempty(tempFit), Fit=[]; return; end

Error in qMRLab>FitGo_FitData (line 406)
FitResults = FitData(data,Model,1);

Error in qMRLab>FitGO_Callback (line 388)
FitGo_FitData(hObject, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in qMRLab (line 41)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)qMRLab('FitGO_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
```

**Comment by agahkarakuzu** [comment]
![image](https://user-images.githubusercontent.com/9632322/152021780-f0773dca-3cfb-40d2-8acb-06a603fd4f20.png)

I used the data and TEs to fit a T2 map, ~180ms for the sample. Which qMRLab version are you using? This was an old bug which was resolved.

**Comment by AlexMorello** [comment]
> ![image](https://user-images.githubusercontent.com/9632322/152021780-f0773dca-3cfb-40d2-8acb-06a603fd4f20.png)
> 
> I used the data and TEs to fit a T2 map, ~180ms for the sample. Which qMRLab version are you using? This was an old bug which was resolved.

Hmm - it's 2.4.1. Seems to be the current version. I've tested it on two computers.

**Comment by agahkarakuzu** [comment]
> Hmm - it's 2.4.1. Seems to be the current version.

Can you try using [this version](https://github.com/qMRLab/qMRLab/archive/refs/heads/master.zip) and see if it resolves the issue?

**Comment by AlexMorello** [comment]
Doing that now. By the way, attempting the same in the CLI yields this error: 

```
Reference to non-existent field 'sanityCheck'.

Error in FitData (line 37)
Model.sanityCheck(data);
```

**Comment by agahkarakuzu** [comment]
Can you please give me a more complete information about how are you running into a problem? Are you using a script, if so can you share that script? Or are you using GUI etc.

**Comment by AlexMorello** [comment]
> Can you please give me a more complete information about how are you running into a problem? Are you using a script, if so can you share that script? Or are you using GUI etc.

2.4.**1**.:  GUI on the first attempt, then tried to do the same the CLI way.
2.4.**2**. (thought 2.4.1 was current): GUI yields this:

```
<< i >> Operation has been started:  mono_t2 
<< : >> Parallel:  2 workers 
<< : >> Granularity:  3 
<< : >> Input is split into  6 chunks. 
<< - >> Modal windows have been disabled 
<< ! >> Temporary results will be saved every 5 minutes. 
        + Each data chunk will be saved upon completion. 
  0%[>                                                  ]
Solution not found for the voxel [1,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Solution not found for the voxel [191,65,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Solution not found for the voxel [192,65,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
 17%[========>                                          ]
Solution not found for the voxel [2,1,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
 33%[=================>                                 ]
Solution not found for the voxel [191,129,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Solution not found for the voxel [192,129,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Errorenous fit warnings are now silenced for the chunk 5.
Solution not found for the voxel [1,33,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Solution not found for the voxel [191,33,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
 50%[=========================>                         ]
Solution not found for the voxel [191,161,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Solution not found for the voxel [192,161,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
 67%[=================================>                 ]
Solution not found for the voxel [191,97,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
Solution not found for the voxel [192,97,1]: Objective function is returning undefined values at initial point. lsqnonlin cannot continue. 
100%[===================================================]
Elapsed time is 86.741707 seconds.
 
Was it the same for you?
```

**Comment by agahkarakuzu** [comment]
So using GUI, you got a T2 map. Those warnings are normal, it is using multicores and informing you that there are not solution for some voxels (background). 

If you have no further issues I am closing the issue.

**Comment by AlexMorello** [comment]
> So using GUI, you got a T2 map. Those warnings are normal, it is using multicores and informing you that there are not solution for some voxels (background).
> 
> If you have no further issues I am closing the issue.

...using GUI with the version you supplied - which is the true current one, I suppose?

**Comment by agahkarakuzu** [comment]
...yes

**Comment by AlexMorello** [comment]
> ...yes

Got it! I'll now attempt to do the B1+ mapping I referenced in another issue, and will report on that afterwards.
