### ISSUE TITLE
Fit Protocol for Inversion Recovery Data - RAREVTR_bas sequence Failed

### ISSUE THREAD

**Issue by Ricmelis80** [qMRLab/qMRLab#480]
[Hy](url) everyone!

I tried to compute some fitting protocol ( Voxel and ROI fit)  on my own inversion recovery data acquired using RARAVTR_bas sequence   [IRData.nii.gz (https://github.com/qMRLab/qMRLab/files/10133017/IRData.nii.gz)

Every time I got the following error output  " Protocol has 9 rows and input volume IRData has 1 frame"

Can you give me some help/suggestions?..

Thanks in advance!
Riccardo

**Comment by agahkarakuzu** [comment]
Hi,there! 

I cannot see the data right now, but it is likely that your data is  missing a singleton dimension:

X Y 1 Z

It should not be

X Y Z

Z being # of TIs. 

Can you confirm this is the case?

**Comment by agahkarakuzu** [comment]
Okay, I took a look at your data.  I assume that you have 7 TIs, but you do not specify them in the protocol. That's where 9 rows are coming from (that's what we have for the example dataset). 

You can get a T1 map if you set prococols as described in the documentation:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/9632322/205082617-8f22b693-5333-40ad-9a4a-a04d341fe61a.png">

https://qmrlab.readthedocs.io/en/master/inversion_recovery_batch.html

**Comment by Ricmelis80** [comment]
Hy Agah,

Thanks a lot for clarification! Now runs properly
