### ISSUE TITLE
qMRLAB qmt_spgr mask function ignores Mask file

### ISSUE THREAD

**Issue by frankbolton** [qMRLab/qMRLab#487]
qMRLAB qmt_spgr mask function ignores Mask file

## Expected Behavior
When creating a mask with a smaller region of 1's, for the qmt_spgr, fewer voxels should be fitted and the fit should take place more quickly. Additionally, the preview of mask should show the outline of the loaded mask file. 
## Current Behavior
The preview of the mask is always the same mask that is inside the example code (qmt_spgr.zip -> Mask.mat)
This same mask is the only mask that will be used when masking out an ROI for fitting on this dataset. 
This behaviour persists across Docker container restarts even if only the MTData, R1Map and the new square mask are loaded. 

## Possible Solution
Investigate the functionary of the mask is to look for hardcoded mask values that represent the example code. 

## Steps to Reproduce
Load qMRLab with qmt_spgr
The load the three mat files in this shared directory 
https://drive.google.com/drive/folders/1_lEcFmIDavy21JbMYWc6GWu24e3_G7Xu?usp=sharing
Visualize the mask on top of the MTdata to see a brain outline
Try to fit without multithreading to see that 4101 voxels.
## Context (Environment)
I'm learning to use qmt_spgr and QMRlab in general. Not being able to reduce the running time with a mask is a pain but isn't a complete blocker,

qmt_spgr appears to be disregarding the user custom mask

## Detailed Description
bug fix on the mask loading for qmt_spgr

**Comment by mathieuboudreau** [comment]
Hi @frankbolton !

Thanks for opening this issue.

I just checked the files you shared, and it looks like the mask you have been using has been a brain mask, not a

> a smaller region of 1's

Here's how I checked,

<img width="1262" alt="Screenshot 2023-07-04 at 9 21 00 PM" src="https://github.com/qMRLab/qMRLab/assets/1421029/f2325d2e-4d4f-4c16-946d-21e92037df62">

Did you try to create a mask using qMRLab or another software?

**Comment by frankbolton** [comment]
Hi @mathieuboudreau 
I was trying to generate the mask using Octave. 
It turns out it's a user error and not a bug with qMRLab.

This morning I restarted octave and ran the commands to generate the mask without any other values loaded.

```a = zeros(88,128);
a(40:45, 60:65)=1;
imshow(a);
save -mat7-binary 'eroded_square.mat', 'a';
```

Images below show qMRLab behaving properly with the reduced mask:
![mask-good](https://github.com/qMRLab/qMRLab/assets/3038072/140a910e-79ae-45e1-8e01-979ef0dfcfe8)

![fitting fewer voxels](https://github.com/qMRLab/qMRLab/assets/3038072/b0cb2040-d954-40c4-9cb4-e1880e33eec4)

**Comment by mathieuboudreau** [comment]
Great! Happy your issue has been resolved @frankbolton . P.s. due to how octave implements some of its subroutines, fitting complex models like qMT can take much longer than it would on MATLAB. Also, there is a Single Voxel Fit feature that can be used to if this is somewhat what your interested in doing.
