### ISSUE TITLE
Known tissue parameters for Models in documentation?

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#80]
I was wondering today if we should start creating tables of known tissue values for all of the Models to help new users with simulating data or for validation when fitting their first sets of data? All values could be sourced from published work, which would be referenced in the tables. 

If so, would the documentation section be an appropriate location to list those values?

**Comment by tanguyduval** [comment]
We can put this info in model files header to be sure to fill this info for future models and to have access to it in the qMRLab help (Gabriel is currently parsing the header).
We can provide values for WM and GM in the brain.

Shall we look in the literature or do we use values extracted from the example datasets?
